//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: CrawlerMsg.proto
//
//package group.chaoliu.lightchaser.core.transfer.netty.protobuf;
//
//public final class CrawlerMsgProto {
//  private CrawlerMsgProto() {}
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistryLite registry) {
//  }
//
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistry registry) {
//    registerAllExtensions(
//        (com.google.protobuf.ExtensionRegistryLite) registry);
//  }
//  public interface CrawlerMsgOrBuilder extends
//      // @@protoc_insertion_point(interface_extends:protobuf.CrawlerMsg)
//      com.google.protobuf.MessageOrBuilder {
//
//    /**
//     * <code>int32 URLLevel = 1;</code>
//     */
//    int getURLLevel();
//
//    /**
//     * <code>.protobuf.Job job = 2;</code>
//     */
//    boolean hasJob();
//    /**
//     * <code>.protobuf.Job job = 2;</code>
//     */
//    Job getJob();
//    /**
//     * <code>.protobuf.Job job = 2;</code>
//     */
//    JobOrBuilder getJobOrBuilder();
//
//    /**
//     * <code>.protobuf.RequestMessage requestMessage = 3;</code>
//     */
//    boolean hasRequestMessage();
//    /**
//     * <code>.protobuf.RequestMessage requestMessage = 3;</code>
//     */
//    RequestMessage getRequestMessage();
//    /**
//     * <code>.protobuf.RequestMessage requestMessage = 3;</code>
//     */
//    RequestMessageOrBuilder getRequestMessageOrBuilder();
//  }
//  /**
//   * Protobuf type {@code protobuf.CrawlerMsg}
//   */
//  public  static final class CrawlerMsg extends
//      com.google.protobuf.GeneratedMessageV3 implements
//      // @@protoc_insertion_point(message_implements:protobuf.CrawlerMsg)
//      CrawlerMsgOrBuilder {
//    // Use CrawlerMsg.newBuilder() to construct.
//    private CrawlerMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
//      super(builder);
//    }
//    private CrawlerMsg() {
//      uRLLevel_ = 0;
//    }
//
//    @Override
//    public final com.google.protobuf.UnknownFieldSet
//    getUnknownFields() {
//      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
//    }
//    private CrawlerMsg(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      this();
//      int mutable_bitField0_ = 0;
//      try {
//        boolean done = false;
//        while (!done) {
//          int tag = input.readTag();
//          switch (tag) {
//            case 0:
//              done = true;
//              break;
//            default: {
//              if (!input.skipField(tag)) {
//                done = true;
//              }
//              break;
//            }
//            case 8: {
//
//              uRLLevel_ = input.readInt32();
//              break;
//            }
//            case 18: {
//              Job.Builder subBuilder = null;
//              if (job_ != null) {
//                subBuilder = job_.toBuilder();
//              }
//              job_ = input.readMessage(Job.parser(), extensionRegistry);
//              if (subBuilder != null) {
//                subBuilder.mergeFrom(job_);
//                job_ = subBuilder.buildPartial();
//              }
//
//              break;
//            }
//            case 26: {
//              RequestMessage.Builder subBuilder = null;
//              if (requestMessage_ != null) {
//                subBuilder = requestMessage_.toBuilder();
//              }
//              requestMessage_ = input.readMessage(RequestMessage.parser(), extensionRegistry);
//              if (subBuilder != null) {
//                subBuilder.mergeFrom(requestMessage_);
//                requestMessage_ = subBuilder.buildPartial();
//              }
//
//              break;
//            }
//          }
//        }
//      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//        throw e.setUnfinishedMessage(this);
//      } catch (java.io.IOException e) {
//        throw new com.google.protobuf.InvalidProtocolBufferException(
//            e).setUnfinishedMessage(this);
//      } finally {
//        makeExtensionsImmutable();
//      }
//    }
//    public static final com.google.protobuf.Descriptors.Descriptor
//        getDescriptor() {
//      return CrawlerMsgProto.internal_static_protobuf_CrawlerMsg_descriptor;
//    }
//
//    protected FieldAccessorTable
//        internalGetFieldAccessorTable() {
//      return CrawlerMsgProto.internal_static_protobuf_CrawlerMsg_fieldAccessorTable
//          .ensureFieldAccessorsInitialized(
//              CrawlerMsg.class, Builder.class);
//    }
//
//    public static final int URLLEVEL_FIELD_NUMBER = 1;
//    private int uRLLevel_;
//    /**
//     * <code>int32 URLLevel = 1;</code>
//     */
//    public int getURLLevel() {
//      return uRLLevel_;
//    }
//
//    public static final int JOB_FIELD_NUMBER = 2;
//    private Job job_;
//    /**
//     * <code>.protobuf.Job job = 2;</code>
//     */
//    public boolean hasJob() {
//      return job_ != null;
//    }
//    /**
//     * <code>.protobuf.Job job = 2;</code>
//     */
//    public Job getJob() {
//      return job_ == null ? Job.getDefaultInstance() : job_;
//    }
//    /**
//     * <code>.protobuf.Job job = 2;</code>
//     */
//    public JobOrBuilder getJobOrBuilder() {
//      return getJob();
//    }
//
//    public static final int REQUESTMESSAGE_FIELD_NUMBER = 3;
//    private RequestMessage requestMessage_;
//    /**
//     * <code>.protobuf.RequestMessage requestMessage = 3;</code>
//     */
//    public boolean hasRequestMessage() {
//      return requestMessage_ != null;
//    }
//    /**
//     * <code>.protobuf.RequestMessage requestMessage = 3;</code>
//     */
//    public RequestMessage getRequestMessage() {
//      return requestMessage_ == null ? RequestMessage.getDefaultInstance() : requestMessage_;
//    }
//    /**
//     * <code>.protobuf.RequestMessage requestMessage = 3;</code>
//     */
//    public RequestMessageOrBuilder getRequestMessageOrBuilder() {
//      return getRequestMessage();
//    }
//
//    private byte memoizedIsInitialized = -1;
//    public final boolean isInitialized() {
//      byte isInitialized = memoizedIsInitialized;
//      if (isInitialized == 1) return true;
//      if (isInitialized == 0) return false;
//
//      memoizedIsInitialized = 1;
//      return true;
//    }
//
//    public void writeTo(com.google.protobuf.CodedOutputStream output)
//                        throws java.io.IOException {
//      if (uRLLevel_ != 0) {
//        output.writeInt32(1, uRLLevel_);
//      }
//      if (job_ != null) {
//        output.writeMessage(2, getJob());
//      }
//      if (requestMessage_ != null) {
//        output.writeMessage(3, getRequestMessage());
//      }
//    }
//
//    public int getSerializedSize() {
//      int size = memoizedSize;
//      if (size != -1) return size;
//
//      size = 0;
//      if (uRLLevel_ != 0) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeInt32Size(1, uRLLevel_);
//      }
//      if (job_ != null) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeMessageSize(2, getJob());
//      }
//      if (requestMessage_ != null) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeMessageSize(3, getRequestMessage());
//      }
//      memoizedSize = size;
//      return size;
//    }
//
//    private static final long serialVersionUID = 0L;
//    @Override
//    public boolean equals(final Object obj) {
//      if (obj == this) {
//       return true;
//      }
//      if (!(obj instanceof CrawlerMsg)) {
//        return super.equals(obj);
//      }
//      CrawlerMsg other = (CrawlerMsg) obj;
//
//      boolean result = true;
//      result = result && (getURLLevel()
//          == other.getURLLevel());
//      result = result && (hasJob() == other.hasJob());
//      if (hasJob()) {
//        result = result && getJob()
//            .equals(other.getJob());
//      }
//      result = result && (hasRequestMessage() == other.hasRequestMessage());
//      if (hasRequestMessage()) {
//        result = result && getRequestMessage()
//            .equals(other.getRequestMessage());
//      }
//      return result;
//    }
//
//    @Override
//    public int hashCode() {
//      if (memoizedHashCode != 0) {
//        return memoizedHashCode;
//      }
//      int hash = 41;
//      hash = (19 * hash) + getDescriptor().hashCode();
//      hash = (37 * hash) + URLLEVEL_FIELD_NUMBER;
//      hash = (53 * hash) + getURLLevel();
//      if (hasJob()) {
//        hash = (37 * hash) + JOB_FIELD_NUMBER;
//        hash = (53 * hash) + getJob().hashCode();
//      }
//      if (hasRequestMessage()) {
//        hash = (37 * hash) + REQUESTMESSAGE_FIELD_NUMBER;
//        hash = (53 * hash) + getRequestMessage().hashCode();
//      }
//      hash = (29 * hash) + unknownFields.hashCode();
//      memoizedHashCode = hash;
//      return hash;
//    }
//
//    public static CrawlerMsg parseFrom(
//        java.nio.ByteBuffer data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static CrawlerMsg parseFrom(
//        java.nio.ByteBuffer data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static CrawlerMsg parseFrom(
//        com.google.protobuf.ByteString data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static CrawlerMsg parseFrom(
//        com.google.protobuf.ByteString data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static CrawlerMsg parseFrom(byte[] data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static CrawlerMsg parseFrom(
//        byte[] data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static CrawlerMsg parseFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static CrawlerMsg parseFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static CrawlerMsg parseDelimitedFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input);
//    }
//    public static CrawlerMsg parseDelimitedFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static CrawlerMsg parseFrom(
//        com.google.protobuf.CodedInputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static CrawlerMsg parseFrom(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    public Builder newBuilderForType() { return newBuilder(); }
//    public static Builder newBuilder() {
//      return DEFAULT_INSTANCE.toBuilder();
//    }
//    public static Builder newBuilder(CrawlerMsg prototype) {
//      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//    }
//    public Builder toBuilder() {
//      return this == DEFAULT_INSTANCE
//          ? new Builder() : new Builder().mergeFrom(this);
//    }
//
//    @Override
//    protected Builder newBuilderForType(
//        BuilderParent parent) {
//      Builder builder = new Builder(parent);
//      return builder;
//    }
//    /**
//     * Protobuf type {@code protobuf.CrawlerMsg}
//     */
//    public static final class Builder extends
//        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
//        // @@protoc_insertion_point(builder_implements:protobuf.CrawlerMsg)
//        CrawlerMsgOrBuilder {
//      public static final com.google.protobuf.Descriptors.Descriptor
//          getDescriptor() {
//        return CrawlerMsgProto.internal_static_protobuf_CrawlerMsg_descriptor;
//      }
//
//      protected FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return CrawlerMsgProto.internal_static_protobuf_CrawlerMsg_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                CrawlerMsg.class, Builder.class);
//      }
//
//      // Construct using group.chaoliu.lightchaser.core.transfer.netty.protobuf.CrawlerMsgProto.CrawlerMsg.newBuilder()
//      private Builder() {
//        maybeForceBuilderInitialization();
//      }
//
//      private Builder(
//          BuilderParent parent) {
//        super(parent);
//        maybeForceBuilderInitialization();
//      }
//      private void maybeForceBuilderInitialization() {
//        if (com.google.protobuf.GeneratedMessageV3
//                .alwaysUseFieldBuilders) {
//        }
//      }
//      public Builder clear() {
//        super.clear();
//        uRLLevel_ = 0;
//
//        if (jobBuilder_ == null) {
//          job_ = null;
//        } else {
//          job_ = null;
//          jobBuilder_ = null;
//        }
//        if (requestMessageBuilder_ == null) {
//          requestMessage_ = null;
//        } else {
//          requestMessage_ = null;
//          requestMessageBuilder_ = null;
//        }
//        return this;
//      }
//
//      public com.google.protobuf.Descriptors.Descriptor
//          getDescriptorForType() {
//        return CrawlerMsgProto.internal_static_protobuf_CrawlerMsg_descriptor;
//      }
//
//      public CrawlerMsg getDefaultInstanceForType() {
//        return CrawlerMsg.getDefaultInstance();
//      }
//
//      public CrawlerMsg build() {
//        CrawlerMsg result = buildPartial();
//        if (!result.isInitialized()) {
//          throw newUninitializedMessageException(result);
//        }
//        return result;
//      }
//
//      public CrawlerMsg buildPartial() {
//        CrawlerMsg result = new CrawlerMsg(this);
//        result.uRLLevel_ = uRLLevel_;
//        if (jobBuilder_ == null) {
//          result.job_ = job_;
//        } else {
//          result.job_ = jobBuilder_.build();
//        }
//        if (requestMessageBuilder_ == null) {
//          result.requestMessage_ = requestMessage_;
//        } else {
//          result.requestMessage_ = requestMessageBuilder_.build();
//        }
//        onBuilt();
//        return result;
//      }
//
//      public Builder clone() {
//        return (Builder) super.clone();
//      }
//      public Builder setField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          Object value) {
//        return (Builder) super.setField(field, value);
//      }
//      public Builder clearField(
//          com.google.protobuf.Descriptors.FieldDescriptor field) {
//        return (Builder) super.clearField(field);
//      }
//      public Builder clearOneof(
//          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
//        return (Builder) super.clearOneof(oneof);
//      }
//      public Builder setRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          int index, Object value) {
//        return (Builder) super.setRepeatedField(field, index, value);
//      }
//      public Builder addRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          Object value) {
//        return (Builder) super.addRepeatedField(field, value);
//      }
//      public Builder mergeFrom(com.google.protobuf.Message other) {
//        if (other instanceof CrawlerMsg) {
//          return mergeFrom((CrawlerMsg)other);
//        } else {
//          super.mergeFrom(other);
//          return this;
//        }
//      }
//
//      public Builder mergeFrom(CrawlerMsg other) {
//        if (other == CrawlerMsg.getDefaultInstance()) return this;
//        if (other.getURLLevel() != 0) {
//          setURLLevel(other.getURLLevel());
//        }
//        if (other.hasJob()) {
//          mergeJob(other.getJob());
//        }
//        if (other.hasRequestMessage()) {
//          mergeRequestMessage(other.getRequestMessage());
//        }
//        onChanged();
//        return this;
//      }
//
//      public final boolean isInitialized() {
//        return true;
//      }
//
//      public Builder mergeFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        CrawlerMsg parsedMessage = null;
//        try {
//          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          parsedMessage = (CrawlerMsg) e.getUnfinishedMessage();
//          throw e.unwrapIOException();
//        } finally {
//          if (parsedMessage != null) {
//            mergeFrom(parsedMessage);
//          }
//        }
//        return this;
//      }
//
//      private int uRLLevel_ ;
//      /**
//       * <code>int32 URLLevel = 1;</code>
//       */
//      public int getURLLevel() {
//        return uRLLevel_;
//      }
//      /**
//       * <code>int32 URLLevel = 1;</code>
//       */
//      public Builder setURLLevel(int value) {
//
//        uRLLevel_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>int32 URLLevel = 1;</code>
//       */
//      public Builder clearURLLevel() {
//
//        uRLLevel_ = 0;
//        onChanged();
//        return this;
//      }
//
//      private Job job_ = null;
//      private com.google.protobuf.SingleFieldBuilderV3<
//          Job, Job.Builder, JobOrBuilder> jobBuilder_;
//      /**
//       * <code>.protobuf.Job job = 2;</code>
//       */
//      public boolean hasJob() {
//        return jobBuilder_ != null || job_ != null;
//      }
//      /**
//       * <code>.protobuf.Job job = 2;</code>
//       */
//      public Job getJob() {
//        if (jobBuilder_ == null) {
//          return job_ == null ? Job.getDefaultInstance() : job_;
//        } else {
//          return jobBuilder_.getMessage();
//        }
//      }
//      /**
//       * <code>.protobuf.Job job = 2;</code>
//       */
//      public Builder setJob(Job value) {
//        if (jobBuilder_ == null) {
//          if (value == null) {
//            throw new NullPointerException();
//          }
//          job_ = value;
//          onChanged();
//        } else {
//          jobBuilder_.setMessage(value);
//        }
//
//        return this;
//      }
//      /**
//       * <code>.protobuf.Job job = 2;</code>
//       */
//      public Builder setJob(
//          Job.Builder builderForValue) {
//        if (jobBuilder_ == null) {
//          job_ = builderForValue.build();
//          onChanged();
//        } else {
//          jobBuilder_.setMessage(builderForValue.build());
//        }
//
//        return this;
//      }
//      /**
//       * <code>.protobuf.Job job = 2;</code>
//       */
//      public Builder mergeJob(Job value) {
//        if (jobBuilder_ == null) {
//          if (job_ != null) {
//            job_ =
//              Job.newBuilder(job_).mergeFrom(value).buildPartial();
//          } else {
//            job_ = value;
//          }
//          onChanged();
//        } else {
//          jobBuilder_.mergeFrom(value);
//        }
//
//        return this;
//      }
//      /**
//       * <code>.protobuf.Job job = 2;</code>
//       */
//      public Builder clearJob() {
//        if (jobBuilder_ == null) {
//          job_ = null;
//          onChanged();
//        } else {
//          job_ = null;
//          jobBuilder_ = null;
//        }
//
//        return this;
//      }
//      /**
//       * <code>.protobuf.Job job = 2;</code>
//       */
//      public Job.Builder getJobBuilder() {
//
//        onChanged();
//        return getJobFieldBuilder().getBuilder();
//      }
//      /**
//       * <code>.protobuf.Job job = 2;</code>
//       */
//      public JobOrBuilder getJobOrBuilder() {
//        if (jobBuilder_ != null) {
//          return jobBuilder_.getMessageOrBuilder();
//        } else {
//          return job_ == null ?
//              Job.getDefaultInstance() : job_;
//        }
//      }
//      /**
//       * <code>.protobuf.Job job = 2;</code>
//       */
//      private com.google.protobuf.SingleFieldBuilderV3<
//          Job, Job.Builder, JobOrBuilder>
//          getJobFieldBuilder() {
//        if (jobBuilder_ == null) {
//          jobBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
//              Job, Job.Builder, JobOrBuilder>(
//                  getJob(),
//                  getParentForChildren(),
//                  isClean());
//          job_ = null;
//        }
//        return jobBuilder_;
//      }
//
//      private RequestMessage requestMessage_ = null;
//      private com.google.protobuf.SingleFieldBuilderV3<
//          RequestMessage, RequestMessage.Builder, RequestMessageOrBuilder> requestMessageBuilder_;
//      /**
//       * <code>.protobuf.RequestMessage requestMessage = 3;</code>
//       */
//      public boolean hasRequestMessage() {
//        return requestMessageBuilder_ != null || requestMessage_ != null;
//      }
//      /**
//       * <code>.protobuf.RequestMessage requestMessage = 3;</code>
//       */
//      public RequestMessage getRequestMessage() {
//        if (requestMessageBuilder_ == null) {
//          return requestMessage_ == null ? RequestMessage.getDefaultInstance() : requestMessage_;
//        } else {
//          return requestMessageBuilder_.getMessage();
//        }
//      }
//      /**
//       * <code>.protobuf.RequestMessage requestMessage = 3;</code>
//       */
//      public Builder setRequestMessage(RequestMessage value) {
//        if (requestMessageBuilder_ == null) {
//          if (value == null) {
//            throw new NullPointerException();
//          }
//          requestMessage_ = value;
//          onChanged();
//        } else {
//          requestMessageBuilder_.setMessage(value);
//        }
//
//        return this;
//      }
//      /**
//       * <code>.protobuf.RequestMessage requestMessage = 3;</code>
//       */
//      public Builder setRequestMessage(
//          RequestMessage.Builder builderForValue) {
//        if (requestMessageBuilder_ == null) {
//          requestMessage_ = builderForValue.build();
//          onChanged();
//        } else {
//          requestMessageBuilder_.setMessage(builderForValue.build());
//        }
//
//        return this;
//      }
//      /**
//       * <code>.protobuf.RequestMessage requestMessage = 3;</code>
//       */
//      public Builder mergeRequestMessage(RequestMessage value) {
//        if (requestMessageBuilder_ == null) {
//          if (requestMessage_ != null) {
//            requestMessage_ =
//              RequestMessage.newBuilder(requestMessage_).mergeFrom(value).buildPartial();
//          } else {
//            requestMessage_ = value;
//          }
//          onChanged();
//        } else {
//          requestMessageBuilder_.mergeFrom(value);
//        }
//
//        return this;
//      }
//      /**
//       * <code>.protobuf.RequestMessage requestMessage = 3;</code>
//       */
//      public Builder clearRequestMessage() {
//        if (requestMessageBuilder_ == null) {
//          requestMessage_ = null;
//          onChanged();
//        } else {
//          requestMessage_ = null;
//          requestMessageBuilder_ = null;
//        }
//
//        return this;
//      }
//      /**
//       * <code>.protobuf.RequestMessage requestMessage = 3;</code>
//       */
//      public RequestMessage.Builder getRequestMessageBuilder() {
//
//        onChanged();
//        return getRequestMessageFieldBuilder().getBuilder();
//      }
//      /**
//       * <code>.protobuf.RequestMessage requestMessage = 3;</code>
//       */
//      public RequestMessageOrBuilder getRequestMessageOrBuilder() {
//        if (requestMessageBuilder_ != null) {
//          return requestMessageBuilder_.getMessageOrBuilder();
//        } else {
//          return requestMessage_ == null ?
//              RequestMessage.getDefaultInstance() : requestMessage_;
//        }
//      }
//      /**
//       * <code>.protobuf.RequestMessage requestMessage = 3;</code>
//       */
//      private com.google.protobuf.SingleFieldBuilderV3<
//          RequestMessage, RequestMessage.Builder, RequestMessageOrBuilder>
//          getRequestMessageFieldBuilder() {
//        if (requestMessageBuilder_ == null) {
//          requestMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
//              RequestMessage, RequestMessage.Builder, RequestMessageOrBuilder>(
//                  getRequestMessage(),
//                  getParentForChildren(),
//                  isClean());
//          requestMessage_ = null;
//        }
//        return requestMessageBuilder_;
//      }
//      public final Builder setUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return this;
//      }
//
//      public final Builder mergeUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return this;
//      }
//
//
//      // @@protoc_insertion_point(builder_scope:protobuf.CrawlerMsg)
//    }
//
//    // @@protoc_insertion_point(class_scope:protobuf.CrawlerMsg)
//    private static final CrawlerMsg DEFAULT_INSTANCE;
//    static {
//      DEFAULT_INSTANCE = new CrawlerMsg();
//    }
//
//    public static CrawlerMsg getDefaultInstance() {
//      return DEFAULT_INSTANCE;
//    }
//
//    private static final com.google.protobuf.Parser<CrawlerMsg>
//        PARSER = new com.google.protobuf.AbstractParser<CrawlerMsg>() {
//      public CrawlerMsg parsePartialFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//          return new CrawlerMsg(input, extensionRegistry);
//      }
//    };
//
//    public static com.google.protobuf.Parser<CrawlerMsg> parser() {
//      return PARSER;
//    }
//
//    @Override
//    public com.google.protobuf.Parser<CrawlerMsg> getParserForType() {
//      return PARSER;
//    }
//
//    public CrawlerMsg getDefaultInstanceForType() {
//      return DEFAULT_INSTANCE;
//    }
//
//  }
//
//  public interface JobOrBuilder extends
//      // @@protoc_insertion_point(interface_extends:protobuf.Job)
//      com.google.protobuf.MessageOrBuilder {
//
//    /**
//     * <code>string type = 1;</code>
//     */
//    String getType();
//    /**
//     * <code>string type = 1;</code>
//     */
//    com.google.protobuf.ByteString
//        getTypeBytes();
//
//    /**
//     * <code>string name = 2;</code>
//     */
//    String getName();
//    /**
//     * <code>string name = 2;</code>
//     */
//    com.google.protobuf.ByteString
//        getNameBytes();
//  }
//  /**
//   * Protobuf type {@code protobuf.Job}
//   */
//  public  static final class Job extends
//      com.google.protobuf.GeneratedMessageV3 implements
//      // @@protoc_insertion_point(message_implements:protobuf.Job)
//      JobOrBuilder {
//    // Use Job.newBuilder() to construct.
//    private Job(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
//      super(builder);
//    }
//    private Job() {
//      type_ = "";
//      name_ = "";
//    }
//
//    @Override
//    public final com.google.protobuf.UnknownFieldSet
//    getUnknownFields() {
//      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
//    }
//    private Job(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      this();
//      int mutable_bitField0_ = 0;
//      try {
//        boolean done = false;
//        while (!done) {
//          int tag = input.readTag();
//          switch (tag) {
//            case 0:
//              done = true;
//              break;
//            default: {
//              if (!input.skipField(tag)) {
//                done = true;
//              }
//              break;
//            }
//            case 10: {
//              String s = input.readStringRequireUtf8();
//
//              type_ = s;
//              break;
//            }
//            case 18: {
//              String s = input.readStringRequireUtf8();
//
//              name_ = s;
//              break;
//            }
//          }
//        }
//      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//        throw e.setUnfinishedMessage(this);
//      } catch (java.io.IOException e) {
//        throw new com.google.protobuf.InvalidProtocolBufferException(
//            e).setUnfinishedMessage(this);
//      } finally {
//        makeExtensionsImmutable();
//      }
//    }
//    public static final com.google.protobuf.Descriptors.Descriptor
//        getDescriptor() {
//      return CrawlerMsgProto.internal_static_protobuf_Job_descriptor;
//    }
//
//    protected FieldAccessorTable
//        internalGetFieldAccessorTable() {
//      return CrawlerMsgProto.internal_static_protobuf_Job_fieldAccessorTable
//          .ensureFieldAccessorsInitialized(
//              Job.class, Builder.class);
//    }
//
//    public static final int TYPE_FIELD_NUMBER = 1;
//    private volatile Object type_;
//    /**
//     * <code>string type = 1;</code>
//     */
//    public String getType() {
//      Object ref = type_;
//      if (ref instanceof String) {
//        return (String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        String s = bs.toStringUtf8();
//        type_ = s;
//        return s;
//      }
//    }
//    /**
//     * <code>string type = 1;</code>
//     */
//    public com.google.protobuf.ByteString
//        getTypeBytes() {
//      Object ref = type_;
//      if (ref instanceof String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (String) ref);
//        type_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int NAME_FIELD_NUMBER = 2;
//    private volatile Object name_;
//    /**
//     * <code>string name = 2;</code>
//     */
//    public String getName() {
//      Object ref = name_;
//      if (ref instanceof String) {
//        return (String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        String s = bs.toStringUtf8();
//        name_ = s;
//        return s;
//      }
//    }
//    /**
//     * <code>string name = 2;</code>
//     */
//    public com.google.protobuf.ByteString
//        getNameBytes() {
//      Object ref = name_;
//      if (ref instanceof String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (String) ref);
//        name_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    private byte memoizedIsInitialized = -1;
//    public final boolean isInitialized() {
//      byte isInitialized = memoizedIsInitialized;
//      if (isInitialized == 1) return true;
//      if (isInitialized == 0) return false;
//
//      memoizedIsInitialized = 1;
//      return true;
//    }
//
//    public void writeTo(com.google.protobuf.CodedOutputStream output)
//                        throws java.io.IOException {
//      if (!getTypeBytes().isEmpty()) {
//        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
//      }
//      if (!getNameBytes().isEmpty()) {
//        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
//      }
//    }
//
//    public int getSerializedSize() {
//      int size = memoizedSize;
//      if (size != -1) return size;
//
//      size = 0;
//      if (!getTypeBytes().isEmpty()) {
//        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
//      }
//      if (!getNameBytes().isEmpty()) {
//        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
//      }
//      memoizedSize = size;
//      return size;
//    }
//
//    private static final long serialVersionUID = 0L;
//    @Override
//    public boolean equals(final Object obj) {
//      if (obj == this) {
//       return true;
//      }
//      if (!(obj instanceof Job)) {
//        return super.equals(obj);
//      }
//      Job other = (Job) obj;
//
//      boolean result = true;
//      result = result && getType()
//          .equals(other.getType());
//      result = result && getName()
//          .equals(other.getName());
//      return result;
//    }
//
//    @Override
//    public int hashCode() {
//      if (memoizedHashCode != 0) {
//        return memoizedHashCode;
//      }
//      int hash = 41;
//      hash = (19 * hash) + getDescriptor().hashCode();
//      hash = (37 * hash) + TYPE_FIELD_NUMBER;
//      hash = (53 * hash) + getType().hashCode();
//      hash = (37 * hash) + NAME_FIELD_NUMBER;
//      hash = (53 * hash) + getName().hashCode();
//      hash = (29 * hash) + unknownFields.hashCode();
//      memoizedHashCode = hash;
//      return hash;
//    }
//
//    public static Job parseFrom(
//        java.nio.ByteBuffer data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static Job parseFrom(
//        java.nio.ByteBuffer data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static Job parseFrom(
//        com.google.protobuf.ByteString data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static Job parseFrom(
//        com.google.protobuf.ByteString data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static Job parseFrom(byte[] data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static Job parseFrom(
//        byte[] data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static Job parseFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static Job parseFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static Job parseDelimitedFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input);
//    }
//    public static Job parseDelimitedFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static Job parseFrom(
//        com.google.protobuf.CodedInputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static Job parseFrom(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    public Builder newBuilderForType() { return newBuilder(); }
//    public static Builder newBuilder() {
//      return DEFAULT_INSTANCE.toBuilder();
//    }
//    public static Builder newBuilder(Job prototype) {
//      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//    }
//    public Builder toBuilder() {
//      return this == DEFAULT_INSTANCE
//          ? new Builder() : new Builder().mergeFrom(this);
//    }
//
//    @Override
//    protected Builder newBuilderForType(
//        BuilderParent parent) {
//      Builder builder = new Builder(parent);
//      return builder;
//    }
//    /**
//     * Protobuf type {@code protobuf.Job}
//     */
//    public static final class Builder extends
//        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
//        // @@protoc_insertion_point(builder_implements:protobuf.Job)
//        JobOrBuilder {
//      public static final com.google.protobuf.Descriptors.Descriptor
//          getDescriptor() {
//        return CrawlerMsgProto.internal_static_protobuf_Job_descriptor;
//      }
//
//      protected FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return CrawlerMsgProto.internal_static_protobuf_Job_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                Job.class, Builder.class);
//      }
//
//      // Construct using group.chaoliu.lightchaser.core.transfer.netty.protobuf.CrawlerMsgProto.Job.newBuilder()
//      private Builder() {
//        maybeForceBuilderInitialization();
//      }
//
//      private Builder(
//          BuilderParent parent) {
//        super(parent);
//        maybeForceBuilderInitialization();
//      }
//      private void maybeForceBuilderInitialization() {
//        if (com.google.protobuf.GeneratedMessageV3
//                .alwaysUseFieldBuilders) {
//        }
//      }
//      public Builder clear() {
//        super.clear();
//        type_ = "";
//
//        name_ = "";
//
//        return this;
//      }
//
//      public com.google.protobuf.Descriptors.Descriptor
//          getDescriptorForType() {
//        return CrawlerMsgProto.internal_static_protobuf_Job_descriptor;
//      }
//
//      public Job getDefaultInstanceForType() {
//        return Job.getDefaultInstance();
//      }
//
//      public Job build() {
//        Job result = buildPartial();
//        if (!result.isInitialized()) {
//          throw newUninitializedMessageException(result);
//        }
//        return result;
//      }
//
//      public Job buildPartial() {
//        Job result = new Job(this);
//        result.type_ = type_;
//        result.name_ = name_;
//        onBuilt();
//        return result;
//      }
//
//      public Builder clone() {
//        return (Builder) super.clone();
//      }
//      public Builder setField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          Object value) {
//        return (Builder) super.setField(field, value);
//      }
//      public Builder clearField(
//          com.google.protobuf.Descriptors.FieldDescriptor field) {
//        return (Builder) super.clearField(field);
//      }
//      public Builder clearOneof(
//          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
//        return (Builder) super.clearOneof(oneof);
//      }
//      public Builder setRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          int index, Object value) {
//        return (Builder) super.setRepeatedField(field, index, value);
//      }
//      public Builder addRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          Object value) {
//        return (Builder) super.addRepeatedField(field, value);
//      }
//      public Builder mergeFrom(com.google.protobuf.Message other) {
//        if (other instanceof Job) {
//          return mergeFrom((Job)other);
//        } else {
//          super.mergeFrom(other);
//          return this;
//        }
//      }
//
//      public Builder mergeFrom(Job other) {
//        if (other == Job.getDefaultInstance()) return this;
//        if (!other.getType().isEmpty()) {
//          type_ = other.type_;
//          onChanged();
//        }
//        if (!other.getName().isEmpty()) {
//          name_ = other.name_;
//          onChanged();
//        }
//        onChanged();
//        return this;
//      }
//
//      public final boolean isInitialized() {
//        return true;
//      }
//
//      public Builder mergeFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        Job parsedMessage = null;
//        try {
//          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          parsedMessage = (Job) e.getUnfinishedMessage();
//          throw e.unwrapIOException();
//        } finally {
//          if (parsedMessage != null) {
//            mergeFrom(parsedMessage);
//          }
//        }
//        return this;
//      }
//
//      private Object type_ = "";
//      /**
//       * <code>string type = 1;</code>
//       */
//      public String getType() {
//        Object ref = type_;
//        if (!(ref instanceof String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          String s = bs.toStringUtf8();
//          type_ = s;
//          return s;
//        } else {
//          return (String) ref;
//        }
//      }
//      /**
//       * <code>string type = 1;</code>
//       */
//      public com.google.protobuf.ByteString
//          getTypeBytes() {
//        Object ref = type_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (String) ref);
//          type_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>string type = 1;</code>
//       */
//      public Builder setType(
//          String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//
//        type_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string type = 1;</code>
//       */
//      public Builder clearType() {
//
//        type_ = getDefaultInstance().getType();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string type = 1;</code>
//       */
//      public Builder setTypeBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  checkByteStringIsUtf8(value);
//
//        type_ = value;
//        onChanged();
//        return this;
//      }
//
//      private Object name_ = "";
//      /**
//       * <code>string name = 2;</code>
//       */
//      public String getName() {
//        Object ref = name_;
//        if (!(ref instanceof String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          String s = bs.toStringUtf8();
//          name_ = s;
//          return s;
//        } else {
//          return (String) ref;
//        }
//      }
//      /**
//       * <code>string name = 2;</code>
//       */
//      public com.google.protobuf.ByteString
//          getNameBytes() {
//        Object ref = name_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (String) ref);
//          name_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>string name = 2;</code>
//       */
//      public Builder setName(
//          String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//
//        name_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string name = 2;</code>
//       */
//      public Builder clearName() {
//
//        name_ = getDefaultInstance().getName();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string name = 2;</code>
//       */
//      public Builder setNameBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  checkByteStringIsUtf8(value);
//
//        name_ = value;
//        onChanged();
//        return this;
//      }
//      public final Builder setUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return this;
//      }
//
//      public final Builder mergeUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return this;
//      }
//
//
//      // @@protoc_insertion_point(builder_scope:protobuf.Job)
//    }
//
//    // @@protoc_insertion_point(class_scope:protobuf.Job)
//    private static final Job DEFAULT_INSTANCE;
//    static {
//      DEFAULT_INSTANCE = new Job();
//    }
//
//    public static Job getDefaultInstance() {
//      return DEFAULT_INSTANCE;
//    }
//
//    private static final com.google.protobuf.Parser<Job>
//        PARSER = new com.google.protobuf.AbstractParser<Job>() {
//      public Job parsePartialFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//          return new Job(input, extensionRegistry);
//      }
//    };
//
//    public static com.google.protobuf.Parser<Job> parser() {
//      return PARSER;
//    }
//
//    @Override
//    public com.google.protobuf.Parser<Job> getParserForType() {
//      return PARSER;
//    }
//
//    public Job getDefaultInstanceForType() {
//      return DEFAULT_INSTANCE;
//    }
//
//  }
//
//  public interface RequestMessageOrBuilder extends
//      // @@protoc_insertion_point(interface_extends:protobuf.RequestMessage)
//      com.google.protobuf.MessageOrBuilder {
//
//    /**
//     * <code>string URL = 1;</code>
//     */
//    String getURL();
//    /**
//     * <code>string URL = 1;</code>
//     */
//    com.google.protobuf.ByteString
//        getURLBytes();
//
//    /**
//     * <code>bool isPostRequest = 2;</code>
//     */
//    boolean getIsPostRequest();
//
//    /**
//     * <code>map&lt;string, string&gt; headers = 3;</code>
//     */
//    int getHeadersCount();
//    /**
//     * <code>map&lt;string, string&gt; headers = 3;</code>
//     */
//    boolean containsHeaders(
//            String key);
//    /**
//     * Use {@link #getHeadersMap()} instead.
//     */
//    @Deprecated
//    java.util.Map<String, String>
//    getHeaders();
//    /**
//     * <code>map&lt;string, string&gt; headers = 3;</code>
//     */
//    java.util.Map<String, String>
//    getHeadersMap();
//    /**
//     * <code>map&lt;string, string&gt; headers = 3;</code>
//     */
//
//    String getHeadersOrDefault(
//            String key,
//            String defaultValue);
//    /**
//     * <code>map&lt;string, string&gt; headers = 3;</code>
//     */
//
//    String getHeadersOrThrow(
//            String key);
//
//    /**
//     * <code>map&lt;string, string&gt; cookie = 4;</code>
//     */
//    int getCookieCount();
//    /**
//     * <code>map&lt;string, string&gt; cookie = 4;</code>
//     */
//    boolean containsCookie(
//            String key);
//    /**
//     * Use {@link #getCookieMap()} instead.
//     */
//    @Deprecated
//    java.util.Map<String, String>
//    getCookie();
//    /**
//     * <code>map&lt;string, string&gt; cookie = 4;</code>
//     */
//    java.util.Map<String, String>
//    getCookieMap();
//    /**
//     * <code>map&lt;string, string&gt; cookie = 4;</code>
//     */
//
//    String getCookieOrDefault(
//            String key,
//            String defaultValue);
//    /**
//     * <code>map&lt;string, string&gt; cookie = 4;</code>
//     */
//
//    String getCookieOrThrow(
//            String key);
//  }
//  /**
//   * Protobuf type {@code protobuf.RequestMessage}
//   */
//  public  static final class RequestMessage extends
//      com.google.protobuf.GeneratedMessageV3 implements
//      // @@protoc_insertion_point(message_implements:protobuf.RequestMessage)
//      RequestMessageOrBuilder {
//    // Use RequestMessage.newBuilder() to construct.
//    private RequestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
//      super(builder);
//    }
//    private RequestMessage() {
//      uRL_ = "";
//      isPostRequest_ = false;
//    }
//
//    @Override
//    public final com.google.protobuf.UnknownFieldSet
//    getUnknownFields() {
//      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
//    }
//    private RequestMessage(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      this();
//      int mutable_bitField0_ = 0;
//      try {
//        boolean done = false;
//        while (!done) {
//          int tag = input.readTag();
//          switch (tag) {
//            case 0:
//              done = true;
//              break;
//            default: {
//              if (!input.skipField(tag)) {
//                done = true;
//              }
//              break;
//            }
//            case 10: {
//              String s = input.readStringRequireUtf8();
//
//              uRL_ = s;
//              break;
//            }
//            case 16: {
//
//              isPostRequest_ = input.readBool();
//              break;
//            }
//            case 26: {
//              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
//                headers_ = com.google.protobuf.MapField.newMapField(
//                    HeadersDefaultEntryHolder.defaultEntry);
//                mutable_bitField0_ |= 0x00000004;
//              }
//              com.google.protobuf.MapEntry<String, String>
//              headers__ = input.readMessage(
//                  HeadersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
//              headers_.getMutableMap().put(
//                  headers__.getKey(), headers__.getValue());
//              break;
//            }
//            case 34: {
//              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
//                cookie_ = com.google.protobuf.MapField.newMapField(
//                    CookieDefaultEntryHolder.defaultEntry);
//                mutable_bitField0_ |= 0x00000008;
//              }
//              com.google.protobuf.MapEntry<String, String>
//              cookie__ = input.readMessage(
//                  CookieDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
//              cookie_.getMutableMap().put(
//                  cookie__.getKey(), cookie__.getValue());
//              break;
//            }
//          }
//        }
//      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//        throw e.setUnfinishedMessage(this);
//      } catch (java.io.IOException e) {
//        throw new com.google.protobuf.InvalidProtocolBufferException(
//            e).setUnfinishedMessage(this);
//      } finally {
//        makeExtensionsImmutable();
//      }
//    }
//    public static final com.google.protobuf.Descriptors.Descriptor
//        getDescriptor() {
//      return CrawlerMsgProto.internal_static_protobuf_RequestMessage_descriptor;
//    }
//
//    @SuppressWarnings({"rawtypes"})
//    protected com.google.protobuf.MapField internalGetMapField(
//        int number) {
//      switch (number) {
//        case 3:
//          return internalGetHeaders();
//        case 4:
//          return internalGetCookie();
//        default:
//          throw new RuntimeException(
//              "Invalid map field number: " + number);
//      }
//    }
//    protected FieldAccessorTable
//        internalGetFieldAccessorTable() {
//      return CrawlerMsgProto.internal_static_protobuf_RequestMessage_fieldAccessorTable
//          .ensureFieldAccessorsInitialized(
//              RequestMessage.class, Builder.class);
//    }
//
//    private int bitField0_;
//    public static final int URL_FIELD_NUMBER = 1;
//    private volatile Object uRL_;
//    /**
//     * <code>string URL = 1;</code>
//     */
//    public String getURL() {
//      Object ref = uRL_;
//      if (ref instanceof String) {
//        return (String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        String s = bs.toStringUtf8();
//        uRL_ = s;
//        return s;
//      }
//    }
//    /**
//     * <code>string URL = 1;</code>
//     */
//    public com.google.protobuf.ByteString
//        getURLBytes() {
//      Object ref = uRL_;
//      if (ref instanceof String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (String) ref);
//        uRL_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int ISPOSTREQUEST_FIELD_NUMBER = 2;
//    private boolean isPostRequest_;
//    /**
//     * <code>bool isPostRequest = 2;</code>
//     */
//    public boolean getIsPostRequest() {
//      return isPostRequest_;
//    }
//
//    public static final int HEADERS_FIELD_NUMBER = 3;
//    private static final class HeadersDefaultEntryHolder {
//      static final com.google.protobuf.MapEntry<
//          String, String> defaultEntry =
//              com.google.protobuf.MapEntry
//              .<String, String>newDefaultInstance(
//                  CrawlerMsgProto.internal_static_protobuf_RequestMessage_HeadersEntry_descriptor,
//                  com.google.protobuf.WireFormat.FieldType.STRING,
//                  "",
//                  com.google.protobuf.WireFormat.FieldType.STRING,
//                  "");
//    }
//    private com.google.protobuf.MapField<
//        String, String> headers_;
//    private com.google.protobuf.MapField<String, String>
//    internalGetHeaders() {
//      if (headers_ == null) {
//        return com.google.protobuf.MapField.emptyMapField(
//            HeadersDefaultEntryHolder.defaultEntry);
//      }
//      return headers_;
//    }
//
//    public int getHeadersCount() {
//      return internalGetHeaders().getMap().size();
//    }
//    /**
//     * <code>map&lt;string, string&gt; headers = 3;</code>
//     */
//
//    public boolean containsHeaders(
//        String key) {
//      if (key == null) { throw new NullPointerException(); }
//      return internalGetHeaders().getMap().containsKey(key);
//    }
//    /**
//     * Use {@link #getHeadersMap()} instead.
//     */
//    @Deprecated
//    public java.util.Map<String, String> getHeaders() {
//      return getHeadersMap();
//    }
//    /**
//     * <code>map&lt;string, string&gt; headers = 3;</code>
//     */
//
//    public java.util.Map<String, String> getHeadersMap() {
//      return internalGetHeaders().getMap();
//    }
//    /**
//     * <code>map&lt;string, string&gt; headers = 3;</code>
//     */
//
//    public String getHeadersOrDefault(
//        String key,
//        String defaultValue) {
//      if (key == null) { throw new NullPointerException(); }
//      java.util.Map<String, String> map =
//          internalGetHeaders().getMap();
//      return map.containsKey(key) ? map.get(key) : defaultValue;
//    }
//    /**
//     * <code>map&lt;string, string&gt; headers = 3;</code>
//     */
//
//    public String getHeadersOrThrow(
//        String key) {
//      if (key == null) { throw new NullPointerException(); }
//      java.util.Map<String, String> map =
//          internalGetHeaders().getMap();
//      if (!map.containsKey(key)) {
//        throw new IllegalArgumentException();
//      }
//      return map.get(key);
//    }
//
//    public static final int COOKIE_FIELD_NUMBER = 4;
//    private static final class CookieDefaultEntryHolder {
//      static final com.google.protobuf.MapEntry<
//          String, String> defaultEntry =
//              com.google.protobuf.MapEntry
//              .<String, String>newDefaultInstance(
//                  CrawlerMsgProto.internal_static_protobuf_RequestMessage_CookieEntry_descriptor,
//                  com.google.protobuf.WireFormat.FieldType.STRING,
//                  "",
//                  com.google.protobuf.WireFormat.FieldType.STRING,
//                  "");
//    }
//    private com.google.protobuf.MapField<
//        String, String> cookie_;
//    private com.google.protobuf.MapField<String, String>
//    internalGetCookie() {
//      if (cookie_ == null) {
//        return com.google.protobuf.MapField.emptyMapField(
//            CookieDefaultEntryHolder.defaultEntry);
//      }
//      return cookie_;
//    }
//
//    public int getCookieCount() {
//      return internalGetCookie().getMap().size();
//    }
//    /**
//     * <code>map&lt;string, string&gt; cookie = 4;</code>
//     */
//
//    public boolean containsCookie(
//        String key) {
//      if (key == null) { throw new NullPointerException(); }
//      return internalGetCookie().getMap().containsKey(key);
//    }
//    /**
//     * Use {@link #getCookieMap()} instead.
//     */
//    @Deprecated
//    public java.util.Map<String, String> getCookie() {
//      return getCookieMap();
//    }
//    /**
//     * <code>map&lt;string, string&gt; cookie = 4;</code>
//     */
//
//    public java.util.Map<String, String> getCookieMap() {
//      return internalGetCookie().getMap();
//    }
//    /**
//     * <code>map&lt;string, string&gt; cookie = 4;</code>
//     */
//
//    public String getCookieOrDefault(
//        String key,
//        String defaultValue) {
//      if (key == null) { throw new NullPointerException(); }
//      java.util.Map<String, String> map =
//          internalGetCookie().getMap();
//      return map.containsKey(key) ? map.get(key) : defaultValue;
//    }
//    /**
//     * <code>map&lt;string, string&gt; cookie = 4;</code>
//     */
//
//    public String getCookieOrThrow(
//        String key) {
//      if (key == null) { throw new NullPointerException(); }
//      java.util.Map<String, String> map =
//          internalGetCookie().getMap();
//      if (!map.containsKey(key)) {
//        throw new IllegalArgumentException();
//      }
//      return map.get(key);
//    }
//
//    private byte memoizedIsInitialized = -1;
//    public final boolean isInitialized() {
//      byte isInitialized = memoizedIsInitialized;
//      if (isInitialized == 1) return true;
//      if (isInitialized == 0) return false;
//
//      memoizedIsInitialized = 1;
//      return true;
//    }
//
//    public void writeTo(com.google.protobuf.CodedOutputStream output)
//                        throws java.io.IOException {
//      if (!getURLBytes().isEmpty()) {
//        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uRL_);
//      }
//      if (isPostRequest_ != false) {
//        output.writeBool(2, isPostRequest_);
//      }
//      com.google.protobuf.GeneratedMessageV3
//        .serializeStringMapTo(
//          output,
//          internalGetHeaders(),
//          HeadersDefaultEntryHolder.defaultEntry,
//          3);
//      com.google.protobuf.GeneratedMessageV3
//        .serializeStringMapTo(
//          output,
//          internalGetCookie(),
//          CookieDefaultEntryHolder.defaultEntry,
//          4);
//    }
//
//    public int getSerializedSize() {
//      int size = memoizedSize;
//      if (size != -1) return size;
//
//      size = 0;
//      if (!getURLBytes().isEmpty()) {
//        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uRL_);
//      }
//      if (isPostRequest_ != false) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeBoolSize(2, isPostRequest_);
//      }
//      for (java.util.Map.Entry<String, String> entry
//           : internalGetHeaders().getMap().entrySet()) {
//        com.google.protobuf.MapEntry<String, String>
//        headers__ = HeadersDefaultEntryHolder.defaultEntry.newBuilderForType()
//            .setKey(entry.getKey())
//            .setValue(entry.getValue())
//            .build();
//        size += com.google.protobuf.CodedOutputStream
//            .computeMessageSize(3, headers__);
//      }
//      for (java.util.Map.Entry<String, String> entry
//           : internalGetCookie().getMap().entrySet()) {
//        com.google.protobuf.MapEntry<String, String>
//        cookie__ = CookieDefaultEntryHolder.defaultEntry.newBuilderForType()
//            .setKey(entry.getKey())
//            .setValue(entry.getValue())
//            .build();
//        size += com.google.protobuf.CodedOutputStream
//            .computeMessageSize(4, cookie__);
//      }
//      memoizedSize = size;
//      return size;
//    }
//
//    private static final long serialVersionUID = 0L;
//    @Override
//    public boolean equals(final Object obj) {
//      if (obj == this) {
//       return true;
//      }
//      if (!(obj instanceof RequestMessage)) {
//        return super.equals(obj);
//      }
//      RequestMessage other = (RequestMessage) obj;
//
//      boolean result = true;
//      result = result && getURL()
//          .equals(other.getURL());
//      result = result && (getIsPostRequest()
//          == other.getIsPostRequest());
//      result = result && internalGetHeaders().equals(
//          other.internalGetHeaders());
//      result = result && internalGetCookie().equals(
//          other.internalGetCookie());
//      return result;
//    }
//
//    @Override
//    public int hashCode() {
//      if (memoizedHashCode != 0) {
//        return memoizedHashCode;
//      }
//      int hash = 41;
//      hash = (19 * hash) + getDescriptor().hashCode();
//      hash = (37 * hash) + URL_FIELD_NUMBER;
//      hash = (53 * hash) + getURL().hashCode();
//      hash = (37 * hash) + ISPOSTREQUEST_FIELD_NUMBER;
//      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
//          getIsPostRequest());
//      if (!internalGetHeaders().getMap().isEmpty()) {
//        hash = (37 * hash) + HEADERS_FIELD_NUMBER;
//        hash = (53 * hash) + internalGetHeaders().hashCode();
//      }
//      if (!internalGetCookie().getMap().isEmpty()) {
//        hash = (37 * hash) + COOKIE_FIELD_NUMBER;
//        hash = (53 * hash) + internalGetCookie().hashCode();
//      }
//      hash = (29 * hash) + unknownFields.hashCode();
//      memoizedHashCode = hash;
//      return hash;
//    }
//
//    public static RequestMessage parseFrom(
//        java.nio.ByteBuffer data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static RequestMessage parseFrom(
//        java.nio.ByteBuffer data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static RequestMessage parseFrom(
//        com.google.protobuf.ByteString data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static RequestMessage parseFrom(
//        com.google.protobuf.ByteString data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static RequestMessage parseFrom(byte[] data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static RequestMessage parseFrom(
//        byte[] data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static RequestMessage parseFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static RequestMessage parseFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static RequestMessage parseDelimitedFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input);
//    }
//    public static RequestMessage parseDelimitedFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static RequestMessage parseFrom(
//        com.google.protobuf.CodedInputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static RequestMessage parseFrom(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    public Builder newBuilderForType() { return newBuilder(); }
//    public static Builder newBuilder() {
//      return DEFAULT_INSTANCE.toBuilder();
//    }
//    public static Builder newBuilder(RequestMessage prototype) {
//      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//    }
//    public Builder toBuilder() {
//      return this == DEFAULT_INSTANCE
//          ? new Builder() : new Builder().mergeFrom(this);
//    }
//
//    @Override
//    protected Builder newBuilderForType(
//        BuilderParent parent) {
//      Builder builder = new Builder(parent);
//      return builder;
//    }
//    /**
//     * Protobuf type {@code protobuf.RequestMessage}
//     */
//    public static final class Builder extends
//        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
//        // @@protoc_insertion_point(builder_implements:protobuf.RequestMessage)
//        RequestMessageOrBuilder {
//      public static final com.google.protobuf.Descriptors.Descriptor
//          getDescriptor() {
//        return CrawlerMsgProto.internal_static_protobuf_RequestMessage_descriptor;
//      }
//
//      @SuppressWarnings({"rawtypes"})
//      protected com.google.protobuf.MapField internalGetMapField(
//          int number) {
//        switch (number) {
//          case 3:
//            return internalGetHeaders();
//          case 4:
//            return internalGetCookie();
//          default:
//            throw new RuntimeException(
//                "Invalid map field number: " + number);
//        }
//      }
//      @SuppressWarnings({"rawtypes"})
//      protected com.google.protobuf.MapField internalGetMutableMapField(
//          int number) {
//        switch (number) {
//          case 3:
//            return internalGetMutableHeaders();
//          case 4:
//            return internalGetMutableCookie();
//          default:
//            throw new RuntimeException(
//                "Invalid map field number: " + number);
//        }
//      }
//      protected FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return CrawlerMsgProto.internal_static_protobuf_RequestMessage_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                RequestMessage.class, Builder.class);
//      }
//
//      // Construct using group.chaoliu.lightchaser.core.transfer.netty.protobuf.CrawlerMsgProto.RequestMessage.newBuilder()
//      private Builder() {
//        maybeForceBuilderInitialization();
//      }
//
//      private Builder(
//          BuilderParent parent) {
//        super(parent);
//        maybeForceBuilderInitialization();
//      }
//      private void maybeForceBuilderInitialization() {
//        if (com.google.protobuf.GeneratedMessageV3
//                .alwaysUseFieldBuilders) {
//        }
//      }
//      public Builder clear() {
//        super.clear();
//        uRL_ = "";
//
//        isPostRequest_ = false;
//
//        internalGetMutableHeaders().clear();
//        internalGetMutableCookie().clear();
//        return this;
//      }
//
//      public com.google.protobuf.Descriptors.Descriptor
//          getDescriptorForType() {
//        return CrawlerMsgProto.internal_static_protobuf_RequestMessage_descriptor;
//      }
//
//      public RequestMessage getDefaultInstanceForType() {
//        return RequestMessage.getDefaultInstance();
//      }
//
//      public RequestMessage build() {
//        RequestMessage result = buildPartial();
//        if (!result.isInitialized()) {
//          throw newUninitializedMessageException(result);
//        }
//        return result;
//      }
//
//      public RequestMessage buildPartial() {
//        RequestMessage result = new RequestMessage(this);
//        int from_bitField0_ = bitField0_;
//        int to_bitField0_ = 0;
//        result.uRL_ = uRL_;
//        result.isPostRequest_ = isPostRequest_;
//        result.headers_ = internalGetHeaders();
//        result.headers_.makeImmutable();
//        result.cookie_ = internalGetCookie();
//        result.cookie_.makeImmutable();
//        result.bitField0_ = to_bitField0_;
//        onBuilt();
//        return result;
//      }
//
//      public Builder clone() {
//        return (Builder) super.clone();
//      }
//      public Builder setField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          Object value) {
//        return (Builder) super.setField(field, value);
//      }
//      public Builder clearField(
//          com.google.protobuf.Descriptors.FieldDescriptor field) {
//        return (Builder) super.clearField(field);
//      }
//      public Builder clearOneof(
//          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
//        return (Builder) super.clearOneof(oneof);
//      }
//      public Builder setRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          int index, Object value) {
//        return (Builder) super.setRepeatedField(field, index, value);
//      }
//      public Builder addRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          Object value) {
//        return (Builder) super.addRepeatedField(field, value);
//      }
//      public Builder mergeFrom(com.google.protobuf.Message other) {
//        if (other instanceof RequestMessage) {
//          return mergeFrom((RequestMessage)other);
//        } else {
//          super.mergeFrom(other);
//          return this;
//        }
//      }
//
//      public Builder mergeFrom(RequestMessage other) {
//        if (other == RequestMessage.getDefaultInstance()) return this;
//        if (!other.getURL().isEmpty()) {
//          uRL_ = other.uRL_;
//          onChanged();
//        }
//        if (other.getIsPostRequest() != false) {
//          setIsPostRequest(other.getIsPostRequest());
//        }
//        internalGetMutableHeaders().mergeFrom(
//            other.internalGetHeaders());
//        internalGetMutableCookie().mergeFrom(
//            other.internalGetCookie());
//        onChanged();
//        return this;
//      }
//
//      public final boolean isInitialized() {
//        return true;
//      }
//
//      public Builder mergeFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        RequestMessage parsedMessage = null;
//        try {
//          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          parsedMessage = (RequestMessage) e.getUnfinishedMessage();
//          throw e.unwrapIOException();
//        } finally {
//          if (parsedMessage != null) {
//            mergeFrom(parsedMessage);
//          }
//        }
//        return this;
//      }
//      private int bitField0_;
//
//      private Object uRL_ = "";
//      /**
//       * <code>string URL = 1;</code>
//       */
//      public String getURL() {
//        Object ref = uRL_;
//        if (!(ref instanceof String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          String s = bs.toStringUtf8();
//          uRL_ = s;
//          return s;
//        } else {
//          return (String) ref;
//        }
//      }
//      /**
//       * <code>string URL = 1;</code>
//       */
//      public com.google.protobuf.ByteString
//          getURLBytes() {
//        Object ref = uRL_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (String) ref);
//          uRL_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>string URL = 1;</code>
//       */
//      public Builder setURL(
//          String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//
//        uRL_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string URL = 1;</code>
//       */
//      public Builder clearURL() {
//
//        uRL_ = getDefaultInstance().getURL();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string URL = 1;</code>
//       */
//      public Builder setURLBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  checkByteStringIsUtf8(value);
//
//        uRL_ = value;
//        onChanged();
//        return this;
//      }
//
//      private boolean isPostRequest_ ;
//      /**
//       * <code>bool isPostRequest = 2;</code>
//       */
//      public boolean getIsPostRequest() {
//        return isPostRequest_;
//      }
//      /**
//       * <code>bool isPostRequest = 2;</code>
//       */
//      public Builder setIsPostRequest(boolean value) {
//
//        isPostRequest_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>bool isPostRequest = 2;</code>
//       */
//      public Builder clearIsPostRequest() {
//
//        isPostRequest_ = false;
//        onChanged();
//        return this;
//      }
//
//      private com.google.protobuf.MapField<
//          String, String> headers_;
//      private com.google.protobuf.MapField<String, String>
//      internalGetHeaders() {
//        if (headers_ == null) {
//          return com.google.protobuf.MapField.emptyMapField(
//              HeadersDefaultEntryHolder.defaultEntry);
//        }
//        return headers_;
//      }
//      private com.google.protobuf.MapField<String, String>
//      internalGetMutableHeaders() {
//        onChanged();;
//        if (headers_ == null) {
//          headers_ = com.google.protobuf.MapField.newMapField(
//              HeadersDefaultEntryHolder.defaultEntry);
//        }
//        if (!headers_.isMutable()) {
//          headers_ = headers_.copy();
//        }
//        return headers_;
//      }
//
//      public int getHeadersCount() {
//        return internalGetHeaders().getMap().size();
//      }
//      /**
//       * <code>map&lt;string, string&gt; headers = 3;</code>
//       */
//
//      public boolean containsHeaders(
//          String key) {
//        if (key == null) { throw new NullPointerException(); }
//        return internalGetHeaders().getMap().containsKey(key);
//      }
//      /**
//       * Use {@link #getHeadersMap()} instead.
//       */
//      @Deprecated
//      public java.util.Map<String, String> getHeaders() {
//        return getHeadersMap();
//      }
//      /**
//       * <code>map&lt;string, string&gt; headers = 3;</code>
//       */
//
//      public java.util.Map<String, String> getHeadersMap() {
//        return internalGetHeaders().getMap();
//      }
//      /**
//       * <code>map&lt;string, string&gt; headers = 3;</code>
//       */
//
//      public String getHeadersOrDefault(
//          String key,
//          String defaultValue) {
//        if (key == null) { throw new NullPointerException(); }
//        java.util.Map<String, String> map =
//            internalGetHeaders().getMap();
//        return map.containsKey(key) ? map.get(key) : defaultValue;
//      }
//      /**
//       * <code>map&lt;string, string&gt; headers = 3;</code>
//       */
//
//      public String getHeadersOrThrow(
//          String key) {
//        if (key == null) { throw new NullPointerException(); }
//        java.util.Map<String, String> map =
//            internalGetHeaders().getMap();
//        if (!map.containsKey(key)) {
//          throw new IllegalArgumentException();
//        }
//        return map.get(key);
//      }
//
//      public Builder clearHeaders() {
//        internalGetMutableHeaders().getMutableMap()
//            .clear();
//        return this;
//      }
//      /**
//       * <code>map&lt;string, string&gt; headers = 3;</code>
//       */
//
//      public Builder removeHeaders(
//          String key) {
//        if (key == null) { throw new NullPointerException(); }
//        internalGetMutableHeaders().getMutableMap()
//            .remove(key);
//        return this;
//      }
//      /**
//       * Use alternate mutation accessors instead.
//       */
//      @Deprecated
//      public java.util.Map<String, String>
//      getMutableHeaders() {
//        return internalGetMutableHeaders().getMutableMap();
//      }
//      /**
//       * <code>map&lt;string, string&gt; headers = 3;</code>
//       */
//      public Builder putHeaders(
//          String key,
//          String value) {
//        if (key == null) { throw new NullPointerException(); }
//        if (value == null) { throw new NullPointerException(); }
//        internalGetMutableHeaders().getMutableMap()
//            .put(key, value);
//        return this;
//      }
//      /**
//       * <code>map&lt;string, string&gt; headers = 3;</code>
//       */
//
//      public Builder putAllHeaders(
//          java.util.Map<String, String> values) {
//        internalGetMutableHeaders().getMutableMap()
//            .putAll(values);
//        return this;
//      }
//
//      private com.google.protobuf.MapField<
//          String, String> cookie_;
//      private com.google.protobuf.MapField<String, String>
//      internalGetCookie() {
//        if (cookie_ == null) {
//          return com.google.protobuf.MapField.emptyMapField(
//              CookieDefaultEntryHolder.defaultEntry);
//        }
//        return cookie_;
//      }
//      private com.google.protobuf.MapField<String, String>
//      internalGetMutableCookie() {
//        onChanged();;
//        if (cookie_ == null) {
//          cookie_ = com.google.protobuf.MapField.newMapField(
//              CookieDefaultEntryHolder.defaultEntry);
//        }
//        if (!cookie_.isMutable()) {
//          cookie_ = cookie_.copy();
//        }
//        return cookie_;
//      }
//
//      public int getCookieCount() {
//        return internalGetCookie().getMap().size();
//      }
//      /**
//       * <code>map&lt;string, string&gt; cookie = 4;</code>
//       */
//
//      public boolean containsCookie(
//          String key) {
//        if (key == null) { throw new NullPointerException(); }
//        return internalGetCookie().getMap().containsKey(key);
//      }
//      /**
//       * Use {@link #getCookieMap()} instead.
//       */
//      @Deprecated
//      public java.util.Map<String, String> getCookie() {
//        return getCookieMap();
//      }
//      /**
//       * <code>map&lt;string, string&gt; cookie = 4;</code>
//       */
//
//      public java.util.Map<String, String> getCookieMap() {
//        return internalGetCookie().getMap();
//      }
//      /**
//       * <code>map&lt;string, string&gt; cookie = 4;</code>
//       */
//
//      public String getCookieOrDefault(
//          String key,
//          String defaultValue) {
//        if (key == null) { throw new NullPointerException(); }
//        java.util.Map<String, String> map =
//            internalGetCookie().getMap();
//        return map.containsKey(key) ? map.get(key) : defaultValue;
//      }
//      /**
//       * <code>map&lt;string, string&gt; cookie = 4;</code>
//       */
//
//      public String getCookieOrThrow(
//          String key) {
//        if (key == null) { throw new NullPointerException(); }
//        java.util.Map<String, String> map =
//            internalGetCookie().getMap();
//        if (!map.containsKey(key)) {
//          throw new IllegalArgumentException();
//        }
//        return map.get(key);
//      }
//
//      public Builder clearCookie() {
//        internalGetMutableCookie().getMutableMap()
//            .clear();
//        return this;
//      }
//      /**
//       * <code>map&lt;string, string&gt; cookie = 4;</code>
//       */
//
//      public Builder removeCookie(
//          String key) {
//        if (key == null) { throw new NullPointerException(); }
//        internalGetMutableCookie().getMutableMap()
//            .remove(key);
//        return this;
//      }
//      /**
//       * Use alternate mutation accessors instead.
//       */
//      @Deprecated
//      public java.util.Map<String, String>
//      getMutableCookie() {
//        return internalGetMutableCookie().getMutableMap();
//      }
//      /**
//       * <code>map&lt;string, string&gt; cookie = 4;</code>
//       */
//      public Builder putCookie(
//          String key,
//          String value) {
//        if (key == null) { throw new NullPointerException(); }
//        if (value == null) { throw new NullPointerException(); }
//        internalGetMutableCookie().getMutableMap()
//            .put(key, value);
//        return this;
//      }
//      /**
//       * <code>map&lt;string, string&gt; cookie = 4;</code>
//       */
//
//      public Builder putAllCookie(
//          java.util.Map<String, String> values) {
//        internalGetMutableCookie().getMutableMap()
//            .putAll(values);
//        return this;
//      }
//      public final Builder setUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return this;
//      }
//
//      public final Builder mergeUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return this;
//      }
//
//
//      // @@protoc_insertion_point(builder_scope:protobuf.RequestMessage)
//    }
//
//    // @@protoc_insertion_point(class_scope:protobuf.RequestMessage)
//    private static final RequestMessage DEFAULT_INSTANCE;
//    static {
//      DEFAULT_INSTANCE = new RequestMessage();
//    }
//
//    public static RequestMessage getDefaultInstance() {
//      return DEFAULT_INSTANCE;
//    }
//
//    private static final com.google.protobuf.Parser<RequestMessage>
//        PARSER = new com.google.protobuf.AbstractParser<RequestMessage>() {
//      public RequestMessage parsePartialFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//          return new RequestMessage(input, extensionRegistry);
//      }
//    };
//
//    public static com.google.protobuf.Parser<RequestMessage> parser() {
//      return PARSER;
//    }
//
//    @Override
//    public com.google.protobuf.Parser<RequestMessage> getParserForType() {
//      return PARSER;
//    }
//
//    public RequestMessage getDefaultInstanceForType() {
//      return DEFAULT_INSTANCE;
//    }
//
//  }
//
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_protobuf_CrawlerMsg_descriptor;
//  private static final
//    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//      internal_static_protobuf_CrawlerMsg_fieldAccessorTable;
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_protobuf_Job_descriptor;
//  private static final
//    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//      internal_static_protobuf_Job_fieldAccessorTable;
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_protobuf_RequestMessage_descriptor;
//  private static final
//    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//      internal_static_protobuf_RequestMessage_fieldAccessorTable;
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_protobuf_RequestMessage_HeadersEntry_descriptor;
//  private static final
//    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//      internal_static_protobuf_RequestMessage_HeadersEntry_fieldAccessorTable;
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_protobuf_RequestMessage_CookieEntry_descriptor;
//  private static final
//    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//      internal_static_protobuf_RequestMessage_CookieEntry_fieldAccessorTable;
//
//  public static com.google.protobuf.Descriptors.FileDescriptor
//      getDescriptor() {
//    return descriptor;
//  }
//  private static  com.google.protobuf.Descriptors.FileDescriptor
//      descriptor;
//  static {
//    String[] descriptorData = {
//      "\n\020CrawlerMsg.proto\022\010protobuf\"l\n\nCrawlerM" +
//      "sg\022\020\n\010URLLevel\030\001 \001(\005\022\032\n\003job\030\002 \001(\0132\r.prot" +
//      "obuf.Job\0220\n\016requestMessage\030\003 \001(\0132\030.proto" +
//      "buf.RequestMessage\"!\n\003Job\022\014\n\004type\030\001 \001(\t\022" +
//      "\014\n\004name\030\002 \001(\t\"\201\002\n\016RequestMessage\022\013\n\003URL\030" +
//      "\001 \001(\t\022\025\n\risPostRequest\030\002 \001(\010\0226\n\007headers\030" +
//      "\003 \003(\0132%.protobuf.RequestMessage.HeadersE" +
//      "ntry\0224\n\006cookie\030\004 \003(\0132$.protobuf.RequestM" +
//      "essage.CookieEntry\032.\n\014HeadersEntry\022\013\n\003ke" +
//      "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032-\n\013CookieEntr",
//      "y\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001BI\n6gro" +
//      "up.chaoliu.lightchaser.core.transfer.net" +
//      "ty.protobufB\017CrawlerMsgProtob\006proto3"
//    };
//    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
//        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
//          public com.google.protobuf.ExtensionRegistry assignDescriptors(
//              com.google.protobuf.Descriptors.FileDescriptor root) {
//            descriptor = root;
//            return null;
//          }
//        };
//    com.google.protobuf.Descriptors.FileDescriptor
//      .internalBuildGeneratedFileFrom(descriptorData,
//        new com.google.protobuf.Descriptors.FileDescriptor[] {
//        }, assigner);
//    internal_static_protobuf_CrawlerMsg_descriptor =
//      getDescriptor().getMessageTypes().get(0);
//    internal_static_protobuf_CrawlerMsg_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
//        internal_static_protobuf_CrawlerMsg_descriptor,
//        new String[] { "URLLevel", "Job", "RequestMessage", });
//    internal_static_protobuf_Job_descriptor =
//      getDescriptor().getMessageTypes().get(1);
//    internal_static_protobuf_Job_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
//        internal_static_protobuf_Job_descriptor,
//        new String[] { "Type", "Name", });
//    internal_static_protobuf_RequestMessage_descriptor =
//      getDescriptor().getMessageTypes().get(2);
//    internal_static_protobuf_RequestMessage_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
//        internal_static_protobuf_RequestMessage_descriptor,
//        new String[] { "URL", "IsPostRequest", "Headers", "Cookie", });
//    internal_static_protobuf_RequestMessage_HeadersEntry_descriptor =
//      internal_static_protobuf_RequestMessage_descriptor.getNestedTypes().get(0);
//    internal_static_protobuf_RequestMessage_HeadersEntry_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
//        internal_static_protobuf_RequestMessage_HeadersEntry_descriptor,
//        new String[] { "Key", "Value", });
//    internal_static_protobuf_RequestMessage_CookieEntry_descriptor =
//      internal_static_protobuf_RequestMessage_descriptor.getNestedTypes().get(1);
//    internal_static_protobuf_RequestMessage_CookieEntry_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
//        internal_static_protobuf_RequestMessage_CookieEntry_descriptor,
//        new String[] { "Key", "Value", });
//  }
//
//  // @@protoc_insertion_point(outer_class_scope)
//}
