//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: Message.proto
//
//package group.chaoliu.lightchaser.core.transfer.netty.protobuf;
//
//public final class MessageProto {
//  private MessageProto() {}
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistryLite registry) {
//  }
//
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistry registry) {
//    registerAllExtensions(
//        (com.google.protobuf.ExtensionRegistryLite) registry);
//  }
//  public interface MessageOrBuilder extends
//      // @@protoc_insertion_point(interface_extends:protobuf.Message)
//      com.google.protobuf.MessageOrBuilder {
//
//    /**
//     * <code>.protobuf.CrawlerMsg crawlerMsg = 1;</code>
//     */
//    boolean hasCrawlerMsg();
//    /**
//     * <code>.protobuf.CrawlerMsg crawlerMsg = 1;</code>
//     */
//    CrawlerMsgProto.CrawlerMsg getCrawlerMsg();
//    /**
//     * <code>.protobuf.CrawlerMsg crawlerMsg = 1;</code>
//     */
//    CrawlerMsgProto.CrawlerMsgOrBuilder getCrawlerMsgOrBuilder();
//
//    /**
//     * <code>.protobuf.Heartbeat heartbeat = 2;</code>
//     */
//    boolean hasHeartbeat();
//    /**
//     * <code>.protobuf.Heartbeat heartbeat = 2;</code>
//     */
//    group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.Heartbeat getHeartbeat();
//    /**
//     * <code>.protobuf.Heartbeat heartbeat = 2;</code>
//     */
//    group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.HeartbeatOrBuilder getHeartbeatOrBuilder();
//  }
//  /**
//   * Protobuf type {@code protobuf.Message}
//   */
//  public  static final class Message extends
//      com.google.protobuf.GeneratedMessageV3 implements
//      // @@protoc_insertion_point(message_implements:protobuf.Message)
//      MessageOrBuilder {
//    // Use Message.newBuilder() to construct.
//    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
//      super(builder);
//    }
//    private Message() {
//    }
//
//    @Override
//    public final com.google.protobuf.UnknownFieldSet
//    getUnknownFields() {
//      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
//    }
//    private Message(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      this();
//      int mutable_bitField0_ = 0;
//      try {
//        boolean done = false;
//        while (!done) {
//          int tag = input.readTag();
//          switch (tag) {
//            case 0:
//              done = true;
//              break;
//            default: {
//              if (!input.skipField(tag)) {
//                done = true;
//              }
//              break;
//            }
//            case 10: {
//              CrawlerMsgProto.CrawlerMsg.Builder subBuilder = null;
//              if (crawlerMsg_ != null) {
//                subBuilder = crawlerMsg_.toBuilder();
//              }
//              crawlerMsg_ = input.readMessage(CrawlerMsgProto.CrawlerMsg.parser(), extensionRegistry);
//              if (subBuilder != null) {
//                subBuilder.mergeFrom(crawlerMsg_);
//                crawlerMsg_ = subBuilder.buildPartial();
//              }
//
//              break;
//            }
//            case 18: {
//              group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.Heartbeat.Builder subBuilder = null;
//              if (heartbeat_ != null) {
//                subBuilder = heartbeat_.toBuilder();
//              }
//              heartbeat_ = input.readMessage(group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.Heartbeat.parser(), extensionRegistry);
//              if (subBuilder != null) {
//                subBuilder.mergeFrom(heartbeat_);
//                heartbeat_ = subBuilder.buildPartial();
//              }
//
//              break;
//            }
//          }
//        }
//      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//        throw e.setUnfinishedMessage(this);
//      } catch (java.io.IOException e) {
//        throw new com.google.protobuf.InvalidProtocolBufferException(
//            e).setUnfinishedMessage(this);
//      } finally {
//        makeExtensionsImmutable();
//      }
//    }
//    public static final com.google.protobuf.Descriptors.Descriptor
//        getDescriptor() {
//      return MessageProto.internal_static_protobuf_Message_descriptor;
//    }
//
//    protected FieldAccessorTable
//        internalGetFieldAccessorTable() {
//      return MessageProto.internal_static_protobuf_Message_fieldAccessorTable
//          .ensureFieldAccessorsInitialized(
//              Message.class, Builder.class);
//    }
//
//    public static final int CRAWLERMSG_FIELD_NUMBER = 1;
//    private CrawlerMsgProto.CrawlerMsg crawlerMsg_;
//    /**
//     * <code>.protobuf.CrawlerMsg crawlerMsg = 1;</code>
//     */
//    public boolean hasCrawlerMsg() {
//      return crawlerMsg_ != null;
//    }
//    /**
//     * <code>.protobuf.CrawlerMsg crawlerMsg = 1;</code>
//     */
//    public CrawlerMsgProto.CrawlerMsg getCrawlerMsg() {
//      return crawlerMsg_ == null ? CrawlerMsgProto.CrawlerMsg.getDefaultInstance() : crawlerMsg_;
//    }
//    /**
//     * <code>.protobuf.CrawlerMsg crawlerMsg = 1;</code>
//     */
//    public CrawlerMsgProto.CrawlerMsgOrBuilder getCrawlerMsgOrBuilder() {
//      return getCrawlerMsg();
//    }
//
//    public static final int HEARTBEAT_FIELD_NUMBER = 2;
//    private group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.Heartbeat heartbeat_;
//    /**
//     * <code>.protobuf.Heartbeat heartbeat = 2;</code>
//     */
//    public boolean hasHeartbeat() {
//      return heartbeat_ != null;
//    }
//    /**
//     * <code>.protobuf.Heartbeat heartbeat = 2;</code>
//     */
//    public group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.Heartbeat getHeartbeat() {
//      return heartbeat_ == null ? group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.Heartbeat.getDefaultInstance() : heartbeat_;
//    }
//    /**
//     * <code>.protobuf.Heartbeat heartbeat = 2;</code>
//     */
//    public group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.HeartbeatOrBuilder getHeartbeatOrBuilder() {
//      return getHeartbeat();
//    }
//
//    private byte memoizedIsInitialized = -1;
//    public final boolean isInitialized() {
//      byte isInitialized = memoizedIsInitialized;
//      if (isInitialized == 1) return true;
//      if (isInitialized == 0) return false;
//
//      memoizedIsInitialized = 1;
//      return true;
//    }
//
//    public void writeTo(com.google.protobuf.CodedOutputStream output)
//                        throws java.io.IOException {
//      if (crawlerMsg_ != null) {
//        output.writeMessage(1, getCrawlerMsg());
//      }
//      if (heartbeat_ != null) {
//        output.writeMessage(2, getHeartbeat());
//      }
//    }
//
//    public int getSerializedSize() {
//      int size = memoizedSize;
//      if (size != -1) return size;
//
//      size = 0;
//      if (crawlerMsg_ != null) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeMessageSize(1, getCrawlerMsg());
//      }
//      if (heartbeat_ != null) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeMessageSize(2, getHeartbeat());
//      }
//      memoizedSize = size;
//      return size;
//    }
//
//    private static final long serialVersionUID = 0L;
//    @Override
//    public boolean equals(final Object obj) {
//      if (obj == this) {
//       return true;
//      }
//      if (!(obj instanceof Message)) {
//        return super.equals(obj);
//      }
//      Message other = (Message) obj;
//
//      boolean result = true;
//      result = result && (hasCrawlerMsg() == other.hasCrawlerMsg());
//      if (hasCrawlerMsg()) {
//        result = result && getCrawlerMsg()
//            .equals(other.getCrawlerMsg());
//      }
//      result = result && (hasHeartbeat() == other.hasHeartbeat());
//      if (hasHeartbeat()) {
//        result = result && getHeartbeat()
//            .equals(other.getHeartbeat());
//      }
//      return result;
//    }
//
//    @Override
//    public int hashCode() {
//      if (memoizedHashCode != 0) {
//        return memoizedHashCode;
//      }
//      int hash = 41;
//      hash = (19 * hash) + getDescriptor().hashCode();
//      if (hasCrawlerMsg()) {
//        hash = (37 * hash) + CRAWLERMSG_FIELD_NUMBER;
//        hash = (53 * hash) + getCrawlerMsg().hashCode();
//      }
//      if (hasHeartbeat()) {
//        hash = (37 * hash) + HEARTBEAT_FIELD_NUMBER;
//        hash = (53 * hash) + getHeartbeat().hashCode();
//      }
//      hash = (29 * hash) + unknownFields.hashCode();
//      memoizedHashCode = hash;
//      return hash;
//    }
//
//    public static Message parseFrom(
//        java.nio.ByteBuffer data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static Message parseFrom(
//        java.nio.ByteBuffer data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static Message parseFrom(
//        com.google.protobuf.ByteString data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static Message parseFrom(
//        com.google.protobuf.ByteString data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static Message parseFrom(byte[] data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static Message parseFrom(
//        byte[] data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static Message parseFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static Message parseFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static Message parseDelimitedFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input);
//    }
//    public static Message parseDelimitedFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static Message parseFrom(
//        com.google.protobuf.CodedInputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static Message parseFrom(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    public Builder newBuilderForType() { return newBuilder(); }
//    public static Builder newBuilder() {
//      return DEFAULT_INSTANCE.toBuilder();
//    }
//    public static Builder newBuilder(Message prototype) {
//      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//    }
//    public Builder toBuilder() {
//      return this == DEFAULT_INSTANCE
//          ? new Builder() : new Builder().mergeFrom(this);
//    }
//
//    @Override
//    protected Builder newBuilderForType(
//        BuilderParent parent) {
//      Builder builder = new Builder(parent);
//      return builder;
//    }
//    /**
//     * Protobuf type {@code protobuf.Message}
//     */
//    public static final class Builder extends
//        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
//        // @@protoc_insertion_point(builder_implements:protobuf.Message)
//        MessageOrBuilder {
//      public static final com.google.protobuf.Descriptors.Descriptor
//          getDescriptor() {
//        return MessageProto.internal_static_protobuf_Message_descriptor;
//      }
//
//      protected FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return MessageProto.internal_static_protobuf_Message_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                Message.class, Builder.class);
//      }
//
//      // Construct using group.chaoliu.lightchaser.core.transfer.netty.protobuf.MessageProto.Message.newBuilder()
//      private Builder() {
//        maybeForceBuilderInitialization();
//      }
//
//      private Builder(
//          BuilderParent parent) {
//        super(parent);
//        maybeForceBuilderInitialization();
//      }
//      private void maybeForceBuilderInitialization() {
//        if (com.google.protobuf.GeneratedMessageV3
//                .alwaysUseFieldBuilders) {
//        }
//      }
//      public Builder clear() {
//        super.clear();
//        if (crawlerMsgBuilder_ == null) {
//          crawlerMsg_ = null;
//        } else {
//          crawlerMsg_ = null;
//          crawlerMsgBuilder_ = null;
//        }
//        if (heartbeatBuilder_ == null) {
//          heartbeat_ = null;
//        } else {
//          heartbeat_ = null;
//          heartbeatBuilder_ = null;
//        }
//        return this;
//      }
//
//      public com.google.protobuf.Descriptors.Descriptor
//          getDescriptorForType() {
//        return MessageProto.internal_static_protobuf_Message_descriptor;
//      }
//
//      public Message getDefaultInstanceForType() {
//        return Message.getDefaultInstance();
//      }
//
//      public Message build() {
//        Message result = buildPartial();
//        if (!result.isInitialized()) {
//          throw newUninitializedMessageException(result);
//        }
//        return result;
//      }
//
//      public Message buildPartial() {
//        Message result = new Message(this);
//        if (crawlerMsgBuilder_ == null) {
//          result.crawlerMsg_ = crawlerMsg_;
//        } else {
//          result.crawlerMsg_ = crawlerMsgBuilder_.build();
//        }
//        if (heartbeatBuilder_ == null) {
//          result.heartbeat_ = heartbeat_;
//        } else {
//          result.heartbeat_ = heartbeatBuilder_.build();
//        }
//        onBuilt();
//        return result;
//      }
//
//      public Builder clone() {
//        return (Builder) super.clone();
//      }
//      public Builder setField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          Object value) {
//        return (Builder) super.setField(field, value);
//      }
//      public Builder clearField(
//          com.google.protobuf.Descriptors.FieldDescriptor field) {
//        return (Builder) super.clearField(field);
//      }
//      public Builder clearOneof(
//          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
//        return (Builder) super.clearOneof(oneof);
//      }
//      public Builder setRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          int index, Object value) {
//        return (Builder) super.setRepeatedField(field, index, value);
//      }
//      public Builder addRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          Object value) {
//        return (Builder) super.addRepeatedField(field, value);
//      }
//      public Builder mergeFrom(com.google.protobuf.Message other) {
//        if (other instanceof Message) {
//          return mergeFrom((Message)other);
//        } else {
//          super.mergeFrom(other);
//          return this;
//        }
//      }
//
//      public Builder mergeFrom(Message other) {
//        if (other == Message.getDefaultInstance()) return this;
//        if (other.hasCrawlerMsg()) {
//          mergeCrawlerMsg(other.getCrawlerMsg());
//        }
//        if (other.hasHeartbeat()) {
//          mergeHeartbeat(other.getHeartbeat());
//        }
//        onChanged();
//        return this;
//      }
//
//      public final boolean isInitialized() {
//        return true;
//      }
//
//      public Builder mergeFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        Message parsedMessage = null;
//        try {
//          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          parsedMessage = (Message) e.getUnfinishedMessage();
//          throw e.unwrapIOException();
//        } finally {
//          if (parsedMessage != null) {
//            mergeFrom(parsedMessage);
//          }
//        }
//        return this;
//      }
//
//      private CrawlerMsgProto.CrawlerMsg crawlerMsg_ = null;
//      private com.google.protobuf.SingleFieldBuilderV3<
//          CrawlerMsgProto.CrawlerMsg, CrawlerMsgProto.CrawlerMsg.Builder, CrawlerMsgProto.CrawlerMsgOrBuilder> crawlerMsgBuilder_;
//      /**
//       * <code>.protobuf.CrawlerMsg crawlerMsg = 1;</code>
//       */
//      public boolean hasCrawlerMsg() {
//        return crawlerMsgBuilder_ != null || crawlerMsg_ != null;
//      }
//      /**
//       * <code>.protobuf.CrawlerMsg crawlerMsg = 1;</code>
//       */
//      public CrawlerMsgProto.CrawlerMsg getCrawlerMsg() {
//        if (crawlerMsgBuilder_ == null) {
//          return crawlerMsg_ == null ? CrawlerMsgProto.CrawlerMsg.getDefaultInstance() : crawlerMsg_;
//        } else {
//          return crawlerMsgBuilder_.getMessage();
//        }
//      }
//      /**
//       * <code>.protobuf.CrawlerMsg crawlerMsg = 1;</code>
//       */
//      public Builder setCrawlerMsg(CrawlerMsgProto.CrawlerMsg value) {
//        if (crawlerMsgBuilder_ == null) {
//          if (value == null) {
//            throw new NullPointerException();
//          }
//          crawlerMsg_ = value;
//          onChanged();
//        } else {
//          crawlerMsgBuilder_.setMessage(value);
//        }
//
//        return this;
//      }
//      /**
//       * <code>.protobuf.CrawlerMsg crawlerMsg = 1;</code>
//       */
//      public Builder setCrawlerMsg(
//          CrawlerMsgProto.CrawlerMsg.Builder builderForValue) {
//        if (crawlerMsgBuilder_ == null) {
//          crawlerMsg_ = builderForValue.build();
//          onChanged();
//        } else {
//          crawlerMsgBuilder_.setMessage(builderForValue.build());
//        }
//
//        return this;
//      }
//      /**
//       * <code>.protobuf.CrawlerMsg crawlerMsg = 1;</code>
//       */
//      public Builder mergeCrawlerMsg(CrawlerMsgProto.CrawlerMsg value) {
//        if (crawlerMsgBuilder_ == null) {
//          if (crawlerMsg_ != null) {
//            crawlerMsg_ =
//              CrawlerMsgProto.CrawlerMsg.newBuilder(crawlerMsg_).mergeFrom(value).buildPartial();
//          } else {
//            crawlerMsg_ = value;
//          }
//          onChanged();
//        } else {
//          crawlerMsgBuilder_.mergeFrom(value);
//        }
//
//        return this;
//      }
//      /**
//       * <code>.protobuf.CrawlerMsg crawlerMsg = 1;</code>
//       */
//      public Builder clearCrawlerMsg() {
//        if (crawlerMsgBuilder_ == null) {
//          crawlerMsg_ = null;
//          onChanged();
//        } else {
//          crawlerMsg_ = null;
//          crawlerMsgBuilder_ = null;
//        }
//
//        return this;
//      }
//      /**
//       * <code>.protobuf.CrawlerMsg crawlerMsg = 1;</code>
//       */
//      public CrawlerMsgProto.CrawlerMsg.Builder getCrawlerMsgBuilder() {
//
//        onChanged();
//        return getCrawlerMsgFieldBuilder().getBuilder();
//      }
//      /**
//       * <code>.protobuf.CrawlerMsg crawlerMsg = 1;</code>
//       */
//      public CrawlerMsgProto.CrawlerMsgOrBuilder getCrawlerMsgOrBuilder() {
//        if (crawlerMsgBuilder_ != null) {
//          return crawlerMsgBuilder_.getMessageOrBuilder();
//        } else {
//          return crawlerMsg_ == null ?
//              CrawlerMsgProto.CrawlerMsg.getDefaultInstance() : crawlerMsg_;
//        }
//      }
//      /**
//       * <code>.protobuf.CrawlerMsg crawlerMsg = 1;</code>
//       */
//      private com.google.protobuf.SingleFieldBuilderV3<
//          CrawlerMsgProto.CrawlerMsg, CrawlerMsgProto.CrawlerMsg.Builder, CrawlerMsgProto.CrawlerMsgOrBuilder>
//          getCrawlerMsgFieldBuilder() {
//        if (crawlerMsgBuilder_ == null) {
//          crawlerMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
//              CrawlerMsgProto.CrawlerMsg, CrawlerMsgProto.CrawlerMsg.Builder, CrawlerMsgProto.CrawlerMsgOrBuilder>(
//                  getCrawlerMsg(),
//                  getParentForChildren(),
//                  isClean());
//          crawlerMsg_ = null;
//        }
//        return crawlerMsgBuilder_;
//      }
//
//      private group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.Heartbeat heartbeat_ = null;
//      private com.google.protobuf.SingleFieldBuilderV3<
//          group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.Heartbeat, group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.Heartbeat.Builder, group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.HeartbeatOrBuilder> heartbeatBuilder_;
//      /**
//       * <code>.protobuf.Heartbeat heartbeat = 2;</code>
//       */
//      public boolean hasHeartbeat() {
//        return heartbeatBuilder_ != null || heartbeat_ != null;
//      }
//      /**
//       * <code>.protobuf.Heartbeat heartbeat = 2;</code>
//       */
//      public group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.Heartbeat getHeartbeat() {
//        if (heartbeatBuilder_ == null) {
//          return heartbeat_ == null ? group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.Heartbeat.getDefaultInstance() : heartbeat_;
//        } else {
//          return heartbeatBuilder_.getMessage();
//        }
//      }
//      /**
//       * <code>.protobuf.Heartbeat heartbeat = 2;</code>
//       */
//      public Builder setHeartbeat(group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.Heartbeat value) {
//        if (heartbeatBuilder_ == null) {
//          if (value == null) {
//            throw new NullPointerException();
//          }
//          heartbeat_ = value;
//          onChanged();
//        } else {
//          heartbeatBuilder_.setMessage(value);
//        }
//
//        return this;
//      }
//      /**
//       * <code>.protobuf.Heartbeat heartbeat = 2;</code>
//       */
//      public Builder setHeartbeat(
//          group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.Heartbeat.Builder builderForValue) {
//        if (heartbeatBuilder_ == null) {
//          heartbeat_ = builderForValue.build();
//          onChanged();
//        } else {
//          heartbeatBuilder_.setMessage(builderForValue.build());
//        }
//
//        return this;
//      }
//      /**
//       * <code>.protobuf.Heartbeat heartbeat = 2;</code>
//       */
//      public Builder mergeHeartbeat(group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.Heartbeat value) {
//        if (heartbeatBuilder_ == null) {
//          if (heartbeat_ != null) {
//            heartbeat_ =
//              group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.Heartbeat.newBuilder(heartbeat_).mergeFrom(value).buildPartial();
//          } else {
//            heartbeat_ = value;
//          }
//          onChanged();
//        } else {
//          heartbeatBuilder_.mergeFrom(value);
//        }
//
//        return this;
//      }
//      /**
//       * <code>.protobuf.Heartbeat heartbeat = 2;</code>
//       */
//      public Builder clearHeartbeat() {
//        if (heartbeatBuilder_ == null) {
//          heartbeat_ = null;
//          onChanged();
//        } else {
//          heartbeat_ = null;
//          heartbeatBuilder_ = null;
//        }
//
//        return this;
//      }
//      /**
//       * <code>.protobuf.Heartbeat heartbeat = 2;</code>
//       */
//      public group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.Heartbeat.Builder getHeartbeatBuilder() {
//
//        onChanged();
//        return getHeartbeatFieldBuilder().getBuilder();
//      }
//      /**
//       * <code>.protobuf.Heartbeat heartbeat = 2;</code>
//       */
//      public group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.HeartbeatOrBuilder getHeartbeatOrBuilder() {
//        if (heartbeatBuilder_ != null) {
//          return heartbeatBuilder_.getMessageOrBuilder();
//        } else {
//          return heartbeat_ == null ?
//              group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.Heartbeat.getDefaultInstance() : heartbeat_;
//        }
//      }
//      /**
//       * <code>.protobuf.Heartbeat heartbeat = 2;</code>
//       */
//      private com.google.protobuf.SingleFieldBuilderV3<
//          group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.Heartbeat, group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.Heartbeat.Builder, group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.HeartbeatOrBuilder>
//          getHeartbeatFieldBuilder() {
//        if (heartbeatBuilder_ == null) {
//          heartbeatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
//              group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.Heartbeat, group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.Heartbeat.Builder, group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.HeartbeatOrBuilder>(
//                  getHeartbeat(),
//                  getParentForChildren(),
//                  isClean());
//          heartbeat_ = null;
//        }
//        return heartbeatBuilder_;
//      }
//      public final Builder setUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return this;
//      }
//
//      public final Builder mergeUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return this;
//      }
//
//
//      // @@protoc_insertion_point(builder_scope:protobuf.Message)
//    }
//
//    // @@protoc_insertion_point(class_scope:protobuf.Message)
//    private static final Message DEFAULT_INSTANCE;
//    static {
//      DEFAULT_INSTANCE = new Message();
//    }
//
//    public static Message getDefaultInstance() {
//      return DEFAULT_INSTANCE;
//    }
//
//    private static final com.google.protobuf.Parser<Message>
//        PARSER = new com.google.protobuf.AbstractParser<Message>() {
//      public Message parsePartialFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//          return new Message(input, extensionRegistry);
//      }
//    };
//
//    public static com.google.protobuf.Parser<Message> parser() {
//      return PARSER;
//    }
//
//    @Override
//    public com.google.protobuf.Parser<Message> getParserForType() {
//      return PARSER;
//    }
//
//    public Message getDefaultInstanceForType() {
//      return DEFAULT_INSTANCE;
//    }
//
//  }
//
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_protobuf_Message_descriptor;
//  private static final
//    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//      internal_static_protobuf_Message_fieldAccessorTable;
//
//  public static com.google.protobuf.Descriptors.FileDescriptor
//      getDescriptor() {
//    return descriptor;
//  }
//  private static  com.google.protobuf.Descriptors.FileDescriptor
//      descriptor;
//  static {
//    String[] descriptorData = {
//      "\n\rMessage.proto\022\010protobuf\032\020CrawlerMsg.pr" +
//      "oto\032\017Heartbeat.proto\"[\n\007Message\022(\n\ncrawl" +
//      "erMsg\030\001 \001(\0132\024.protobuf.CrawlerMsg\022&\n\thea" +
//      "rtbeat\030\002 \001(\0132\023.protobuf.HeartbeatBF\n6gro" +
//      "up.chaoliu.lightchaser.core.transfer.net" +
//      "ty.protobufB\014MessageProtob\006proto3"
//    };
//    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
//        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
//          public com.google.protobuf.ExtensionRegistry assignDescriptors(
//              com.google.protobuf.Descriptors.FileDescriptor root) {
//            descriptor = root;
//            return null;
//          }
//        };
//    com.google.protobuf.Descriptors.FileDescriptor
//      .internalBuildGeneratedFileFrom(descriptorData,
//        new com.google.protobuf.Descriptors.FileDescriptor[] {
//          CrawlerMsgProto.getDescriptor(),
//          group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.getDescriptor(),
//        }, assigner);
//    internal_static_protobuf_Message_descriptor =
//      getDescriptor().getMessageTypes().get(0);
//    internal_static_protobuf_Message_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
//        internal_static_protobuf_Message_descriptor,
//        new String[] { "CrawlerMsg", "Heartbeat", });
//    CrawlerMsgProto.getDescriptor();
//    group.chaoliu.lightchaser.core.transfer.netty.protobuf.HeartbeatProto.getDescriptor();
//  }
//
//  // @@protoc_insertion_point(outer_class_scope)
//}
