// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package group.chaoliu.lightchaser.rpc.netty.protobuf;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .protobuf.QueueMsg queueMsg = 1;
    /**
     * <code>optional .protobuf.QueueMsg queueMsg = 1;</code>
     */
    boolean hasQueueMsg();
    /**
     * <code>optional .protobuf.QueueMsg queueMsg = 1;</code>
     */
    QueueMsgProto.QueueMsg getQueueMsg();
    /**
     * <code>optional .protobuf.QueueMsg queueMsg = 1;</code>
     */
    QueueMsgProto.QueueMsgOrBuilder getQueueMsgOrBuilder();

    // optional .protobuf.Heartbeat heartbeat = 2;
    /**
     * <code>optional .protobuf.Heartbeat heartbeat = 2;</code>
     */
    boolean hasHeartbeat();
    /**
     * <code>optional .protobuf.Heartbeat heartbeat = 2;</code>
     */
    HeartbeatProto.Heartbeat getHeartbeat();
    /**
     * <code>optional .protobuf.Heartbeat heartbeat = 2;</code>
     */
    HeartbeatProto.HeartbeatOrBuilder getHeartbeatOrBuilder();

    // optional .protobuf.Message.MsgType msgType = 3 [default = REQ_MSG];
    /**
     * <code>optional .protobuf.Message.MsgType msgType = 3 [default = REQ_MSG];</code>
     */
    boolean hasMsgType();
    /**
     * <code>optional .protobuf.Message.MsgType msgType = 3 [default = REQ_MSG];</code>
     */
    Message.MsgType getMsgType();
  }
  /**
   * Protobuf type {@code protobuf.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage
      implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }

    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              QueueMsgProto.QueueMsg.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = queueMsg_.toBuilder();
              }
              queueMsg_ = input.readMessage(QueueMsgProto.QueueMsg.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(queueMsg_);
                queueMsg_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              HeartbeatProto.Heartbeat.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = heartbeat_.toBuilder();
              }
              heartbeat_ = input.readMessage(HeartbeatProto.Heartbeat.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(heartbeat_);
                heartbeat_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              MsgType value = MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                msgType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProto.internal_static_protobuf_Message_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProto.internal_static_protobuf_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code protobuf.Message.MsgType}
     */
    public enum MsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>REQ_MSG = 0;</code>
       *
       * <pre>
       * 请求消息
       * </pre>
       */
      REQ_MSG(0, 0),
      /**
       * <code>HEART_BEAT = 1;</code>
       *
       * <pre>
       * 心跳
       * </pre>
       */
      HEART_BEAT(1, 1),
      /**
       * <code>CRAWL_MSG = 2;</code>
       *
       * <pre>
       * 爬取信息
       * </pre>
       */
      CRAWL_MSG(2, 2),
      ;

      /**
       * <code>REQ_MSG = 0;</code>
       *
       * <pre>
       * 请求消息
       * </pre>
       */
      public static final int REQ_MSG_VALUE = 0;
      /**
       * <code>HEART_BEAT = 1;</code>
       *
       * <pre>
       * 心跳
       * </pre>
       */
      public static final int HEART_BEAT_VALUE = 1;
      /**
       * <code>CRAWL_MSG = 2;</code>
       *
       * <pre>
       * 爬取信息
       * </pre>
       */
      public static final int CRAWL_MSG_VALUE = 2;


      public final int getNumber() { return value; }

      public static MsgType valueOf(int value) {
        switch (value) {
          case 0: return REQ_MSG;
          case 1: return HEART_BEAT;
          case 2: return CRAWL_MSG;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
              public MsgType findValueByNumber(int number) {
                return MsgType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgType[] VALUES = values();

      public static MsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobuf.Message.MsgType)
    }

    private int bitField0_;
    // optional .protobuf.QueueMsg queueMsg = 1;
    public static final int QUEUEMSG_FIELD_NUMBER = 1;
    private QueueMsgProto.QueueMsg queueMsg_;
    /**
     * <code>optional .protobuf.QueueMsg queueMsg = 1;</code>
     */
    public boolean hasQueueMsg() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .protobuf.QueueMsg queueMsg = 1;</code>
     */
    public QueueMsgProto.QueueMsg getQueueMsg() {
      return queueMsg_;
    }
    /**
     * <code>optional .protobuf.QueueMsg queueMsg = 1;</code>
     */
    public QueueMsgProto.QueueMsgOrBuilder getQueueMsgOrBuilder() {
      return queueMsg_;
    }

    // optional .protobuf.Heartbeat heartbeat = 2;
    public static final int HEARTBEAT_FIELD_NUMBER = 2;
    private HeartbeatProto.Heartbeat heartbeat_;
    /**
     * <code>optional .protobuf.Heartbeat heartbeat = 2;</code>
     */
    public boolean hasHeartbeat() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .protobuf.Heartbeat heartbeat = 2;</code>
     */
    public HeartbeatProto.Heartbeat getHeartbeat() {
      return heartbeat_;
    }
    /**
     * <code>optional .protobuf.Heartbeat heartbeat = 2;</code>
     */
    public HeartbeatProto.HeartbeatOrBuilder getHeartbeatOrBuilder() {
      return heartbeat_;
    }

    // optional .protobuf.Message.MsgType msgType = 3 [default = REQ_MSG];
    public static final int MSGTYPE_FIELD_NUMBER = 3;
    private MsgType msgType_;
    /**
     * <code>optional .protobuf.Message.MsgType msgType = 3 [default = REQ_MSG];</code>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .protobuf.Message.MsgType msgType = 3 [default = REQ_MSG];</code>
     */
    public MsgType getMsgType() {
      return msgType_;
    }

    private void initFields() {
      queueMsg_ = QueueMsgProto.QueueMsg.getDefaultInstance();
      heartbeat_ = HeartbeatProto.Heartbeat.getDefaultInstance();
      msgType_ = MsgType.REQ_MSG;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (hasQueueMsg()) {
        if (!getQueueMsg().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasHeartbeat()) {
        if (!getHeartbeat().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, queueMsg_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, heartbeat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, msgType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, queueMsg_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, heartbeat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, msgType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageProto.internal_static_protobuf_Message_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageProto.internal_static_protobuf_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Message.class, Builder.class);
      }

      // Construct using group.chaoliu.lightchaser.rpc.netty.protobuf.MessageProto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getQueueMsgFieldBuilder();
          getHeartbeatFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (queueMsgBuilder_ == null) {
          queueMsg_ = QueueMsgProto.QueueMsg.getDefaultInstance();
        } else {
          queueMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (heartbeatBuilder_ == null) {
          heartbeat_ = HeartbeatProto.Heartbeat.getDefaultInstance();
        } else {
          heartbeatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        msgType_ = MsgType.REQ_MSG;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageProto.internal_static_protobuf_Message_descriptor;
      }

      public Message getDefaultInstanceForType() {
        return Message.getDefaultInstance();
      }

      public Message build() {
        Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Message buildPartial() {
        Message result = new Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (queueMsgBuilder_ == null) {
          result.queueMsg_ = queueMsg_;
        } else {
          result.queueMsg_ = queueMsgBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (heartbeatBuilder_ == null) {
          result.heartbeat_ = heartbeat_;
        } else {
          result.heartbeat_ = heartbeatBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgType_ = msgType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message) {
          return mergeFrom((Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message other) {
        if (other == Message.getDefaultInstance()) return this;
        if (other.hasQueueMsg()) {
          mergeQueueMsg(other.getQueueMsg());
        }
        if (other.hasHeartbeat()) {
          mergeHeartbeat(other.getHeartbeat());
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasQueueMsg()) {
          if (!getQueueMsg().isInitialized()) {
            
            return false;
          }
        }
        if (hasHeartbeat()) {
          if (!getHeartbeat().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .protobuf.QueueMsg queueMsg = 1;
      private QueueMsgProto.QueueMsg queueMsg_ = QueueMsgProto.QueueMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          QueueMsgProto.QueueMsg, QueueMsgProto.QueueMsg.Builder, QueueMsgProto.QueueMsgOrBuilder> queueMsgBuilder_;
      /**
       * <code>optional .protobuf.QueueMsg queueMsg = 1;</code>
       */
      public boolean hasQueueMsg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .protobuf.QueueMsg queueMsg = 1;</code>
       */
      public QueueMsgProto.QueueMsg getQueueMsg() {
        if (queueMsgBuilder_ == null) {
          return queueMsg_;
        } else {
          return queueMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .protobuf.QueueMsg queueMsg = 1;</code>
       */
      public Builder setQueueMsg(QueueMsgProto.QueueMsg value) {
        if (queueMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          queueMsg_ = value;
          onChanged();
        } else {
          queueMsgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .protobuf.QueueMsg queueMsg = 1;</code>
       */
      public Builder setQueueMsg(
          QueueMsgProto.QueueMsg.Builder builderForValue) {
        if (queueMsgBuilder_ == null) {
          queueMsg_ = builderForValue.build();
          onChanged();
        } else {
          queueMsgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .protobuf.QueueMsg queueMsg = 1;</code>
       */
      public Builder mergeQueueMsg(QueueMsgProto.QueueMsg value) {
        if (queueMsgBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              queueMsg_ != QueueMsgProto.QueueMsg.getDefaultInstance()) {
            queueMsg_ =
              QueueMsgProto.QueueMsg.newBuilder(queueMsg_).mergeFrom(value).buildPartial();
          } else {
            queueMsg_ = value;
          }
          onChanged();
        } else {
          queueMsgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .protobuf.QueueMsg queueMsg = 1;</code>
       */
      public Builder clearQueueMsg() {
        if (queueMsgBuilder_ == null) {
          queueMsg_ = QueueMsgProto.QueueMsg.getDefaultInstance();
          onChanged();
        } else {
          queueMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .protobuf.QueueMsg queueMsg = 1;</code>
       */
      public QueueMsgProto.QueueMsg.Builder getQueueMsgBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getQueueMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .protobuf.QueueMsg queueMsg = 1;</code>
       */
      public QueueMsgProto.QueueMsgOrBuilder getQueueMsgOrBuilder() {
        if (queueMsgBuilder_ != null) {
          return queueMsgBuilder_.getMessageOrBuilder();
        } else {
          return queueMsg_;
        }
      }
      /**
       * <code>optional .protobuf.QueueMsg queueMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          QueueMsgProto.QueueMsg, QueueMsgProto.QueueMsg.Builder, QueueMsgProto.QueueMsgOrBuilder>
          getQueueMsgFieldBuilder() {
        if (queueMsgBuilder_ == null) {
          queueMsgBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              QueueMsgProto.QueueMsg, QueueMsgProto.QueueMsg.Builder, QueueMsgProto.QueueMsgOrBuilder>(
                  queueMsg_,
                  getParentForChildren(),
                  isClean());
          queueMsg_ = null;
        }
        return queueMsgBuilder_;
      }

      // optional .protobuf.Heartbeat heartbeat = 2;
      private HeartbeatProto.Heartbeat heartbeat_ = HeartbeatProto.Heartbeat.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          HeartbeatProto.Heartbeat, HeartbeatProto.Heartbeat.Builder, HeartbeatProto.HeartbeatOrBuilder> heartbeatBuilder_;
      /**
       * <code>optional .protobuf.Heartbeat heartbeat = 2;</code>
       */
      public boolean hasHeartbeat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .protobuf.Heartbeat heartbeat = 2;</code>
       */
      public HeartbeatProto.Heartbeat getHeartbeat() {
        if (heartbeatBuilder_ == null) {
          return heartbeat_;
        } else {
          return heartbeatBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .protobuf.Heartbeat heartbeat = 2;</code>
       */
      public Builder setHeartbeat(HeartbeatProto.Heartbeat value) {
        if (heartbeatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          heartbeat_ = value;
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .protobuf.Heartbeat heartbeat = 2;</code>
       */
      public Builder setHeartbeat(
          HeartbeatProto.Heartbeat.Builder builderForValue) {
        if (heartbeatBuilder_ == null) {
          heartbeat_ = builderForValue.build();
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .protobuf.Heartbeat heartbeat = 2;</code>
       */
      public Builder mergeHeartbeat(HeartbeatProto.Heartbeat value) {
        if (heartbeatBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              heartbeat_ != HeartbeatProto.Heartbeat.getDefaultInstance()) {
            heartbeat_ =
              HeartbeatProto.Heartbeat.newBuilder(heartbeat_).mergeFrom(value).buildPartial();
          } else {
            heartbeat_ = value;
          }
          onChanged();
        } else {
          heartbeatBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .protobuf.Heartbeat heartbeat = 2;</code>
       */
      public Builder clearHeartbeat() {
        if (heartbeatBuilder_ == null) {
          heartbeat_ = HeartbeatProto.Heartbeat.getDefaultInstance();
          onChanged();
        } else {
          heartbeatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .protobuf.Heartbeat heartbeat = 2;</code>
       */
      public HeartbeatProto.Heartbeat.Builder getHeartbeatBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getHeartbeatFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .protobuf.Heartbeat heartbeat = 2;</code>
       */
      public HeartbeatProto.HeartbeatOrBuilder getHeartbeatOrBuilder() {
        if (heartbeatBuilder_ != null) {
          return heartbeatBuilder_.getMessageOrBuilder();
        } else {
          return heartbeat_;
        }
      }
      /**
       * <code>optional .protobuf.Heartbeat heartbeat = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          HeartbeatProto.Heartbeat, HeartbeatProto.Heartbeat.Builder, HeartbeatProto.HeartbeatOrBuilder>
          getHeartbeatFieldBuilder() {
        if (heartbeatBuilder_ == null) {
          heartbeatBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              HeartbeatProto.Heartbeat, HeartbeatProto.Heartbeat.Builder, HeartbeatProto.HeartbeatOrBuilder>(
                  heartbeat_,
                  getParentForChildren(),
                  isClean());
          heartbeat_ = null;
        }
        return heartbeatBuilder_;
      }

      // optional .protobuf.Message.MsgType msgType = 3 [default = REQ_MSG];
      private MsgType msgType_ = MsgType.REQ_MSG;
      /**
       * <code>optional .protobuf.Message.MsgType msgType = 3 [default = REQ_MSG];</code>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .protobuf.Message.MsgType msgType = 3 [default = REQ_MSG];</code>
       */
      public MsgType getMsgType() {
        return msgType_;
      }
      /**
       * <code>optional .protobuf.Message.MsgType msgType = 3 [default = REQ_MSG];</code>
       */
      public Builder setMsgType(MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .protobuf.Message.MsgType msgType = 3 [default = REQ_MSG];</code>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgType_ = MsgType.REQ_MSG;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.Message)
    }

    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.Message)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rMessage.proto\022\010protobuf\032\016QueueMsg.prot" +
      "o\032\017Heartbeat.proto\"\303\001\n\007Message\022$\n\010queueM" +
      "sg\030\001 \001(\0132\022.protobuf.QueueMsg\022&\n\theartbea" +
      "t\030\002 \001(\0132\023.protobuf.Heartbeat\0223\n\007msgType\030" +
      "\003 \001(\0162\031.protobuf.Message.MsgType:\007REQ_MS" +
      "G\"5\n\007MsgType\022\013\n\007REQ_MSG\020\000\022\016\n\nHEART_BEAT\020" +
      "\001\022\r\n\tCRAWL_MSG\020\002B<\n,group.chaoliu.lightc" +
      "haser.rpc.netty.protobufB\014MessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_Message_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_Message_descriptor,
              new String[] { "QueueMsg", "Heartbeat", "MsgType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          QueueMsgProto.getDescriptor(),
          HeartbeatProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
