// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proxy.proto

package group.chaoliu.lightchaser.rpc.netty.protobuf;

public final class ProxyProto {
  private ProxyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProxyMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .protobuf.Proxy proxy = 1;
    /**
     * <code>optional .protobuf.Proxy proxy = 1;</code>
     */
    boolean hasProxy();
    /**
     * <code>optional .protobuf.Proxy proxy = 1;</code>
     */
    Proxy getProxy();
    /**
     * <code>optional .protobuf.Proxy proxy = 1;</code>
     */
    ProxyOrBuilder getProxyOrBuilder();

    // optional string domainKey = 2;
    /**
     * <code>optional string domainKey = 2;</code>
     */
    boolean hasDomainKey();
    /**
     * <code>optional string domainKey = 2;</code>
     */
    String getDomainKey();
    /**
     * <code>optional string domainKey = 2;</code>
     */
    com.google.protobuf.ByteString
        getDomainKeyBytes();

    // optional string reqId = 3;
    /**
     * <code>optional string reqId = 3;</code>
     *
     * <pre>
     * 请求的UUID
     * </pre>
     */
    boolean hasReqId();
    /**
     * <code>optional string reqId = 3;</code>
     *
     * <pre>
     * 请求的UUID
     * </pre>
     */
    String getReqId();
    /**
     * <code>optional string reqId = 3;</code>
     *
     * <pre>
     * 请求的UUID
     * </pre>
     */
    com.google.protobuf.ByteString
        getReqIdBytes();

    // optional .protobuf.ProxyMsg.MsgType msgType = 4 [default = REQ_MSG];
    /**
     * <code>optional .protobuf.ProxyMsg.MsgType msgType = 4 [default = REQ_MSG];</code>
     */
    boolean hasMsgType();
    /**
     * <code>optional .protobuf.ProxyMsg.MsgType msgType = 4 [default = REQ_MSG];</code>
     */
    ProxyMsg.MsgType getMsgType();
  }
  /**
   * Protobuf type {@code protobuf.ProxyMsg}
   */
  public static final class ProxyMsg extends
      com.google.protobuf.GeneratedMessage
      implements ProxyMsgOrBuilder {
    // Use ProxyMsg.newBuilder() to construct.
    private ProxyMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProxyMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProxyMsg defaultInstance;
    public static ProxyMsg getDefaultInstance() {
      return defaultInstance;
    }

    public ProxyMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProxyMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              Proxy.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = proxy_.toBuilder();
              }
              proxy_ = input.readMessage(Proxy.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(proxy_);
                proxy_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              domainKey_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              reqId_ = input.readBytes();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              MsgType value = MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                msgType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProxyProto.internal_static_protobuf_ProxyMsg_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProxyProto.internal_static_protobuf_ProxyMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProxyMsg.class, Builder.class);
    }

    public static com.google.protobuf.Parser<ProxyMsg> PARSER =
        new com.google.protobuf.AbstractParser<ProxyMsg>() {
      public ProxyMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProxyMsg(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<ProxyMsg> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code protobuf.ProxyMsg.MsgType}
     */
    public enum MsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>REQ_MSG = 0;</code>
       *
       * <pre>
       * 请求消息
       * </pre>
       */
      REQ_MSG(0, 0),
      /**
       * <code>PROXY_MSG = 1;</code>
       *
       * <pre>
       * 代理
       * </pre>
       */
      PROXY_MSG(1, 1),
      /**
       * <code>FEEDBACK_MSG = 2;</code>
       *
       * <pre>
       * 反馈信息
       * </pre>
       */
      FEEDBACK_MSG(2, 2),
      ;

      /**
       * <code>REQ_MSG = 0;</code>
       *
       * <pre>
       * 请求消息
       * </pre>
       */
      public static final int REQ_MSG_VALUE = 0;
      /**
       * <code>PROXY_MSG = 1;</code>
       *
       * <pre>
       * 代理
       * </pre>
       */
      public static final int PROXY_MSG_VALUE = 1;
      /**
       * <code>FEEDBACK_MSG = 2;</code>
       *
       * <pre>
       * 反馈信息
       * </pre>
       */
      public static final int FEEDBACK_MSG_VALUE = 2;


      public final int getNumber() { return value; }

      public static MsgType valueOf(int value) {
        switch (value) {
          case 0: return REQ_MSG;
          case 1: return PROXY_MSG;
          case 2: return FEEDBACK_MSG;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
              public MsgType findValueByNumber(int number) {
                return MsgType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ProxyMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgType[] VALUES = values();

      public static MsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobuf.ProxyMsg.MsgType)
    }

    private int bitField0_;
    // optional .protobuf.Proxy proxy = 1;
    public static final int PROXY_FIELD_NUMBER = 1;
    private Proxy proxy_;
    /**
     * <code>optional .protobuf.Proxy proxy = 1;</code>
     */
    public boolean hasProxy() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .protobuf.Proxy proxy = 1;</code>
     */
    public Proxy getProxy() {
      return proxy_;
    }
    /**
     * <code>optional .protobuf.Proxy proxy = 1;</code>
     */
    public ProxyOrBuilder getProxyOrBuilder() {
      return proxy_;
    }

    // optional string domainKey = 2;
    public static final int DOMAINKEY_FIELD_NUMBER = 2;
    private Object domainKey_;
    /**
     * <code>optional string domainKey = 2;</code>
     */
    public boolean hasDomainKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string domainKey = 2;</code>
     */
    public String getDomainKey() {
      Object ref = domainKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          domainKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string domainKey = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDomainKeyBytes() {
      Object ref = domainKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        domainKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string reqId = 3;
    public static final int REQID_FIELD_NUMBER = 3;
    private Object reqId_;
    /**
     * <code>optional string reqId = 3;</code>
     *
     * <pre>
     * 请求的UUID
     * </pre>
     */
    public boolean hasReqId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string reqId = 3;</code>
     *
     * <pre>
     * 请求的UUID
     * </pre>
     */
    public String getReqId() {
      Object ref = reqId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reqId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string reqId = 3;</code>
     *
     * <pre>
     * 请求的UUID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getReqIdBytes() {
      Object ref = reqId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        reqId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .protobuf.ProxyMsg.MsgType msgType = 4 [default = REQ_MSG];
    public static final int MSGTYPE_FIELD_NUMBER = 4;
    private MsgType msgType_;
    /**
     * <code>optional .protobuf.ProxyMsg.MsgType msgType = 4 [default = REQ_MSG];</code>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .protobuf.ProxyMsg.MsgType msgType = 4 [default = REQ_MSG];</code>
     */
    public MsgType getMsgType() {
      return msgType_;
    }

    private void initFields() {
      proxy_ = Proxy.getDefaultInstance();
      domainKey_ = "";
      reqId_ = "";
      msgType_ = MsgType.REQ_MSG;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (hasProxy()) {
        if (!getProxy().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, proxy_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDomainKeyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getReqIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, msgType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, proxy_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDomainKeyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getReqIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, msgType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ProxyMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProxyMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProxyMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProxyMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProxyMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProxyMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProxyMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProxyMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProxyMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProxyMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProxyMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.ProxyMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProxyMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProxyProto.internal_static_protobuf_ProxyMsg_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProxyProto.internal_static_protobuf_ProxyMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProxyMsg.class, Builder.class);
      }

      // Construct using group.chaoliu.lightchaser.rpc.netty.protobuf.ProxyProto.ProxyMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getProxyFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (proxyBuilder_ == null) {
          proxy_ = Proxy.getDefaultInstance();
        } else {
          proxyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        domainKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        reqId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        msgType_ = MsgType.REQ_MSG;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProxyProto.internal_static_protobuf_ProxyMsg_descriptor;
      }

      public ProxyMsg getDefaultInstanceForType() {
        return ProxyMsg.getDefaultInstance();
      }

      public ProxyMsg build() {
        ProxyMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProxyMsg buildPartial() {
        ProxyMsg result = new ProxyMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (proxyBuilder_ == null) {
          result.proxy_ = proxy_;
        } else {
          result.proxy_ = proxyBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.domainKey_ = domainKey_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.reqId_ = reqId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.msgType_ = msgType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProxyMsg) {
          return mergeFrom((ProxyMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProxyMsg other) {
        if (other == ProxyMsg.getDefaultInstance()) return this;
        if (other.hasProxy()) {
          mergeProxy(other.getProxy());
        }
        if (other.hasDomainKey()) {
          bitField0_ |= 0x00000002;
          domainKey_ = other.domainKey_;
          onChanged();
        }
        if (other.hasReqId()) {
          bitField0_ |= 0x00000004;
          reqId_ = other.reqId_;
          onChanged();
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasProxy()) {
          if (!getProxy().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProxyMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProxyMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .protobuf.Proxy proxy = 1;
      private Proxy proxy_ = Proxy.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Proxy, Proxy.Builder, ProxyOrBuilder> proxyBuilder_;
      /**
       * <code>optional .protobuf.Proxy proxy = 1;</code>
       */
      public boolean hasProxy() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .protobuf.Proxy proxy = 1;</code>
       */
      public Proxy getProxy() {
        if (proxyBuilder_ == null) {
          return proxy_;
        } else {
          return proxyBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .protobuf.Proxy proxy = 1;</code>
       */
      public Builder setProxy(Proxy value) {
        if (proxyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          proxy_ = value;
          onChanged();
        } else {
          proxyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .protobuf.Proxy proxy = 1;</code>
       */
      public Builder setProxy(
          Proxy.Builder builderForValue) {
        if (proxyBuilder_ == null) {
          proxy_ = builderForValue.build();
          onChanged();
        } else {
          proxyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .protobuf.Proxy proxy = 1;</code>
       */
      public Builder mergeProxy(Proxy value) {
        if (proxyBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              proxy_ != Proxy.getDefaultInstance()) {
            proxy_ =
              Proxy.newBuilder(proxy_).mergeFrom(value).buildPartial();
          } else {
            proxy_ = value;
          }
          onChanged();
        } else {
          proxyBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .protobuf.Proxy proxy = 1;</code>
       */
      public Builder clearProxy() {
        if (proxyBuilder_ == null) {
          proxy_ = Proxy.getDefaultInstance();
          onChanged();
        } else {
          proxyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .protobuf.Proxy proxy = 1;</code>
       */
      public Proxy.Builder getProxyBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getProxyFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .protobuf.Proxy proxy = 1;</code>
       */
      public ProxyOrBuilder getProxyOrBuilder() {
        if (proxyBuilder_ != null) {
          return proxyBuilder_.getMessageOrBuilder();
        } else {
          return proxy_;
        }
      }
      /**
       * <code>optional .protobuf.Proxy proxy = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Proxy, Proxy.Builder, ProxyOrBuilder>
          getProxyFieldBuilder() {
        if (proxyBuilder_ == null) {
          proxyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Proxy, Proxy.Builder, ProxyOrBuilder>(
                  proxy_,
                  getParentForChildren(),
                  isClean());
          proxy_ = null;
        }
        return proxyBuilder_;
      }

      // optional string domainKey = 2;
      private Object domainKey_ = "";
      /**
       * <code>optional string domainKey = 2;</code>
       */
      public boolean hasDomainKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string domainKey = 2;</code>
       */
      public String getDomainKey() {
        Object ref = domainKey_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          domainKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string domainKey = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDomainKeyBytes() {
        Object ref = domainKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          domainKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string domainKey = 2;</code>
       */
      public Builder setDomainKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        domainKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string domainKey = 2;</code>
       */
      public Builder clearDomainKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        domainKey_ = getDefaultInstance().getDomainKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string domainKey = 2;</code>
       */
      public Builder setDomainKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        domainKey_ = value;
        onChanged();
        return this;
      }

      // optional string reqId = 3;
      private Object reqId_ = "";
      /**
       * <code>optional string reqId = 3;</code>
       *
       * <pre>
       * 请求的UUID
       * </pre>
       */
      public boolean hasReqId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string reqId = 3;</code>
       *
       * <pre>
       * 请求的UUID
       * </pre>
       */
      public String getReqId() {
        Object ref = reqId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          reqId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string reqId = 3;</code>
       *
       * <pre>
       * 请求的UUID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getReqIdBytes() {
        Object ref = reqId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          reqId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string reqId = 3;</code>
       *
       * <pre>
       * 请求的UUID
       * </pre>
       */
      public Builder setReqId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        reqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string reqId = 3;</code>
       *
       * <pre>
       * 请求的UUID
       * </pre>
       */
      public Builder clearReqId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        reqId_ = getDefaultInstance().getReqId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string reqId = 3;</code>
       *
       * <pre>
       * 请求的UUID
       * </pre>
       */
      public Builder setReqIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        reqId_ = value;
        onChanged();
        return this;
      }

      // optional .protobuf.ProxyMsg.MsgType msgType = 4 [default = REQ_MSG];
      private MsgType msgType_ = MsgType.REQ_MSG;
      /**
       * <code>optional .protobuf.ProxyMsg.MsgType msgType = 4 [default = REQ_MSG];</code>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .protobuf.ProxyMsg.MsgType msgType = 4 [default = REQ_MSG];</code>
       */
      public MsgType getMsgType() {
        return msgType_;
      }
      /**
       * <code>optional .protobuf.ProxyMsg.MsgType msgType = 4 [default = REQ_MSG];</code>
       */
      public Builder setMsgType(MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .protobuf.ProxyMsg.MsgType msgType = 4 [default = REQ_MSG];</code>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        msgType_ = MsgType.REQ_MSG;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.ProxyMsg)
    }

    static {
      defaultInstance = new ProxyMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.ProxyMsg)
  }

  public interface ProxyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string host = 1;
    /**
     * <code>required string host = 1;</code>
     */
    boolean hasHost();
    /**
     * <code>required string host = 1;</code>
     */
    String getHost();
    /**
     * <code>required string host = 1;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    // required int32 port = 2;
    /**
     * <code>required int32 port = 2;</code>
     */
    boolean hasPort();
    /**
     * <code>required int32 port = 2;</code>
     */
    int getPort();

    // required string type = 3;
    /**
     * <code>required string type = 3;</code>
     *
     * <pre>
     * http or https or socket
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required string type = 3;</code>
     *
     * <pre>
     * http or https or socket
     * </pre>
     */
    String getType();
    /**
     * <code>required string type = 3;</code>
     *
     * <pre>
     * http or https or socket
     * </pre>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    // required int32 code = 4;
    /**
     * <code>required int32 code = 4;</code>
     */
    boolean hasCode();
    /**
     * <code>required int32 code = 4;</code>
     */
    int getCode();
  }
  /**
   * Protobuf type {@code protobuf.Proxy}
   */
  public static final class Proxy extends
      com.google.protobuf.GeneratedMessage
      implements ProxyOrBuilder {
    // Use Proxy.newBuilder() to construct.
    private Proxy(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Proxy(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Proxy defaultInstance;
    public static Proxy getDefaultInstance() {
      return defaultInstance;
    }

    public Proxy getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Proxy(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              host_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              port_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              type_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              code_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProxyProto.internal_static_protobuf_Proxy_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProxyProto.internal_static_protobuf_Proxy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Proxy.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Proxy> PARSER =
        new com.google.protobuf.AbstractParser<Proxy>() {
      public Proxy parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Proxy(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Proxy> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string host = 1;
    public static final int HOST_FIELD_NUMBER = 1;
    private Object host_;
    /**
     * <code>required string host = 1;</code>
     */
    public boolean hasHost() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string host = 1;</code>
     */
    public String getHost() {
      Object ref = host_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          host_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string host = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      Object ref = host_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 port = 2;
    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <code>required int32 port = 2;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 port = 2;</code>
     */
    public int getPort() {
      return port_;
    }

    // required string type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private Object type_;
    /**
     * <code>required string type = 3;</code>
     *
     * <pre>
     * http or https or socket
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string type = 3;</code>
     *
     * <pre>
     * http or https or socket
     * </pre>
     */
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 3;</code>
     *
     * <pre>
     * http or https or socket
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 code = 4;
    public static final int CODE_FIELD_NUMBER = 4;
    private int code_;
    /**
     * <code>required int32 code = 4;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 code = 4;</code>
     */
    public int getCode() {
      return code_;
    }

    private void initFields() {
      host_ = "";
      port_ = 0;
      type_ = "";
      code_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasHost()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getHostBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, port_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, code_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getHostBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, port_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, code_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Proxy parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Proxy parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Proxy parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Proxy parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Proxy parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Proxy parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Proxy parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Proxy parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Proxy parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Proxy parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Proxy prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Proxy}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProxyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProxyProto.internal_static_protobuf_Proxy_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProxyProto.internal_static_protobuf_Proxy_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Proxy.class, Builder.class);
      }

      // Construct using group.chaoliu.lightchaser.rpc.netty.protobuf.ProxyProto.Proxy.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        host_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProxyProto.internal_static_protobuf_Proxy_descriptor;
      }

      public Proxy getDefaultInstanceForType() {
        return Proxy.getDefaultInstance();
      }

      public Proxy build() {
        Proxy result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Proxy buildPartial() {
        Proxy result = new Proxy(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.host_ = host_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.code_ = code_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Proxy) {
          return mergeFrom((Proxy)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Proxy other) {
        if (other == Proxy.getDefaultInstance()) return this;
        if (other.hasHost()) {
          bitField0_ |= 0x00000001;
          host_ = other.host_;
          onChanged();
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000004;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHost()) {
          
          return false;
        }
        if (!hasPort()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Proxy parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Proxy) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string host = 1;
      private Object host_ = "";
      /**
       * <code>required string host = 1;</code>
       */
      public boolean hasHost() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string host = 1;</code>
       */
      public String getHost() {
        Object ref = host_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string host = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string host = 1;</code>
       */
      public Builder setHost(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string host = 1;</code>
       */
      public Builder clearHost() {
        bitField0_ = (bitField0_ & ~0x00000001);
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>required string host = 1;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        host_ = value;
        onChanged();
        return this;
      }

      // required int32 port = 2;
      private int port_ ;
      /**
       * <code>required int32 port = 2;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 port = 2;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>required int32 port = 2;</code>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000002;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 port = 2;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = 0;
        onChanged();
        return this;
      }

      // required string type = 3;
      private Object type_ = "";
      /**
       * <code>required string type = 3;</code>
       *
       * <pre>
       * http or https or socket
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string type = 3;</code>
       *
       * <pre>
       * http or https or socket
       * </pre>
       */
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string type = 3;</code>
       *
       * <pre>
       * http or https or socket
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 3;</code>
       *
       * <pre>
       * http or https or socket
       * </pre>
       */
      public Builder setType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 3;</code>
       *
       * <pre>
       * http or https or socket
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 3;</code>
       *
       * <pre>
       * http or https or socket
       * </pre>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }

      // required int32 code = 4;
      private int code_ ;
      /**
       * <code>required int32 code = 4;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 code = 4;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>required int32 code = 4;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000008;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 code = 4;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        code_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.Proxy)
    }

    static {
      defaultInstance = new Proxy(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.Proxy)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_ProxyMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_ProxyMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Proxy_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Proxy_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013Proxy.proto\022\010protobuf\"\273\001\n\010ProxyMsg\022\036\n\005" +
      "proxy\030\001 \001(\0132\017.protobuf.Proxy\022\021\n\tdomainKe" +
      "y\030\002 \001(\t\022\r\n\005reqId\030\003 \001(\t\0224\n\007msgType\030\004 \001(\0162" +
      "\032.protobuf.ProxyMsg.MsgType:\007REQ_MSG\"7\n\007" +
      "MsgType\022\013\n\007REQ_MSG\020\000\022\r\n\tPROXY_MSG\020\001\022\020\n\014F" +
      "EEDBACK_MSG\020\002\"?\n\005Proxy\022\014\n\004host\030\001 \002(\t\022\014\n\004" +
      "port\030\002 \002(\005\022\014\n\004type\030\003 \002(\t\022\014\n\004code\030\004 \002(\005B:" +
      "\n,group.chaoliu.lightchaser.rpc.netty.pr" +
      "otobufB\nProxyProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_ProxyMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_ProxyMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_ProxyMsg_descriptor,
              new String[] { "Proxy", "DomainKey", "ReqId", "MsgType", });
          internal_static_protobuf_Proxy_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobuf_Proxy_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_Proxy_descriptor,
              new String[] { "Host", "Port", "Type", "Code", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
