// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QueueMsg.proto

package group.chaoliu.lightchaser.rpc.netty.protobuf;

public final class QueueMsgProto {
  private QueueMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface QueueMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 URLLevel = 1;
    /**
     * <code>required int32 URLLevel = 1;</code>
     */
    boolean hasURLLevel();
    /**
     * <code>required int32 URLLevel = 1;</code>
     */
    int getURLLevel();

    // required .protobuf.Category category = 2;
    /**
     * <code>required .protobuf.Category category = 2;</code>
     */
    boolean hasCategory();
    /**
     * <code>required .protobuf.Category category = 2;</code>
     */
    Category getCategory();
    /**
     * <code>required .protobuf.Category category = 2;</code>
     */
    CategoryOrBuilder getCategoryOrBuilder();

    // required .protobuf.RequestMessage requestMessage = 3;
    /**
     * <code>required .protobuf.RequestMessage requestMessage = 3;</code>
     */
    boolean hasRequestMessage();
    /**
     * <code>required .protobuf.RequestMessage requestMessage = 3;</code>
     */
    RequestMessage getRequestMessage();
    /**
     * <code>required .protobuf.RequestMessage requestMessage = 3;</code>
     */
    RequestMessageOrBuilder getRequestMessageOrBuilder();
  }
  /**
   * Protobuf type {@code protobuf.QueueMsg}
   */
  public static final class QueueMsg extends
      com.google.protobuf.GeneratedMessage
      implements QueueMsgOrBuilder {
    // Use QueueMsg.newBuilder() to construct.
    private QueueMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private QueueMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final QueueMsg defaultInstance;
    public static QueueMsg getDefaultInstance() {
      return defaultInstance;
    }

    public QueueMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private QueueMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uRLLevel_ = input.readInt32();
              break;
            }
            case 18: {
              Category.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = category_.toBuilder();
              }
              category_ = input.readMessage(Category.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(category_);
                category_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              RequestMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = requestMessage_.toBuilder();
              }
              requestMessage_ = input.readMessage(RequestMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(requestMessage_);
                requestMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QueueMsgProto.internal_static_protobuf_QueueMsg_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QueueMsgProto.internal_static_protobuf_QueueMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QueueMsg.class, Builder.class);
    }

    public static com.google.protobuf.Parser<QueueMsg> PARSER =
        new com.google.protobuf.AbstractParser<QueueMsg>() {
      public QueueMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueueMsg(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<QueueMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 URLLevel = 1;
    public static final int URLLEVEL_FIELD_NUMBER = 1;
    private int uRLLevel_;
    /**
     * <code>required int32 URLLevel = 1;</code>
     */
    public boolean hasURLLevel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 URLLevel = 1;</code>
     */
    public int getURLLevel() {
      return uRLLevel_;
    }

    // required .protobuf.Category category = 2;
    public static final int CATEGORY_FIELD_NUMBER = 2;
    private Category category_;
    /**
     * <code>required .protobuf.Category category = 2;</code>
     */
    public boolean hasCategory() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .protobuf.Category category = 2;</code>
     */
    public Category getCategory() {
      return category_;
    }
    /**
     * <code>required .protobuf.Category category = 2;</code>
     */
    public CategoryOrBuilder getCategoryOrBuilder() {
      return category_;
    }

    // required .protobuf.RequestMessage requestMessage = 3;
    public static final int REQUESTMESSAGE_FIELD_NUMBER = 3;
    private RequestMessage requestMessage_;
    /**
     * <code>required .protobuf.RequestMessage requestMessage = 3;</code>
     */
    public boolean hasRequestMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .protobuf.RequestMessage requestMessage = 3;</code>
     */
    public RequestMessage getRequestMessage() {
      return requestMessage_;
    }
    /**
     * <code>required .protobuf.RequestMessage requestMessage = 3;</code>
     */
    public RequestMessageOrBuilder getRequestMessageOrBuilder() {
      return requestMessage_;
    }

    private void initFields() {
      uRLLevel_ = 0;
      category_ = Category.getDefaultInstance();
      requestMessage_ = RequestMessage.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasURLLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCategory()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequestMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getCategory().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getRequestMessage().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, uRLLevel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, category_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, requestMessage_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uRLLevel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, category_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, requestMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static QueueMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueueMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueueMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueueMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueueMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static QueueMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static QueueMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static QueueMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static QueueMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static QueueMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(QueueMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.QueueMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements QueueMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QueueMsgProto.internal_static_protobuf_QueueMsg_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QueueMsgProto.internal_static_protobuf_QueueMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QueueMsg.class, Builder.class);
      }

      // Construct using group.chaoliu.lightchaser.rpc.netty.protobuf.QueueMsgProto.QueueMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCategoryFieldBuilder();
          getRequestMessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uRLLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (categoryBuilder_ == null) {
          category_ = Category.getDefaultInstance();
        } else {
          categoryBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (requestMessageBuilder_ == null) {
          requestMessage_ = RequestMessage.getDefaultInstance();
        } else {
          requestMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QueueMsgProto.internal_static_protobuf_QueueMsg_descriptor;
      }

      public QueueMsg getDefaultInstanceForType() {
        return QueueMsg.getDefaultInstance();
      }

      public QueueMsg build() {
        QueueMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public QueueMsg buildPartial() {
        QueueMsg result = new QueueMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uRLLevel_ = uRLLevel_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (categoryBuilder_ == null) {
          result.category_ = category_;
        } else {
          result.category_ = categoryBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (requestMessageBuilder_ == null) {
          result.requestMessage_ = requestMessage_;
        } else {
          result.requestMessage_ = requestMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QueueMsg) {
          return mergeFrom((QueueMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QueueMsg other) {
        if (other == QueueMsg.getDefaultInstance()) return this;
        if (other.hasURLLevel()) {
          setURLLevel(other.getURLLevel());
        }
        if (other.hasCategory()) {
          mergeCategory(other.getCategory());
        }
        if (other.hasRequestMessage()) {
          mergeRequestMessage(other.getRequestMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasURLLevel()) {
          
          return false;
        }
        if (!hasCategory()) {
          
          return false;
        }
        if (!hasRequestMessage()) {
          
          return false;
        }
        if (!getCategory().isInitialized()) {
          
          return false;
        }
        if (!getRequestMessage().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QueueMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QueueMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 URLLevel = 1;
      private int uRLLevel_ ;
      /**
       * <code>required int32 URLLevel = 1;</code>
       */
      public boolean hasURLLevel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 URLLevel = 1;</code>
       */
      public int getURLLevel() {
        return uRLLevel_;
      }
      /**
       * <code>required int32 URLLevel = 1;</code>
       */
      public Builder setURLLevel(int value) {
        bitField0_ |= 0x00000001;
        uRLLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 URLLevel = 1;</code>
       */
      public Builder clearURLLevel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uRLLevel_ = 0;
        onChanged();
        return this;
      }

      // required .protobuf.Category category = 2;
      private Category category_ = Category.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Category, Category.Builder, CategoryOrBuilder> categoryBuilder_;
      /**
       * <code>required .protobuf.Category category = 2;</code>
       */
      public boolean hasCategory() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .protobuf.Category category = 2;</code>
       */
      public Category getCategory() {
        if (categoryBuilder_ == null) {
          return category_;
        } else {
          return categoryBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protobuf.Category category = 2;</code>
       */
      public Builder setCategory(Category value) {
        if (categoryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          category_ = value;
          onChanged();
        } else {
          categoryBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protobuf.Category category = 2;</code>
       */
      public Builder setCategory(
          Category.Builder builderForValue) {
        if (categoryBuilder_ == null) {
          category_ = builderForValue.build();
          onChanged();
        } else {
          categoryBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protobuf.Category category = 2;</code>
       */
      public Builder mergeCategory(Category value) {
        if (categoryBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              category_ != Category.getDefaultInstance()) {
            category_ =
              Category.newBuilder(category_).mergeFrom(value).buildPartial();
          } else {
            category_ = value;
          }
          onChanged();
        } else {
          categoryBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protobuf.Category category = 2;</code>
       */
      public Builder clearCategory() {
        if (categoryBuilder_ == null) {
          category_ = Category.getDefaultInstance();
          onChanged();
        } else {
          categoryBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .protobuf.Category category = 2;</code>
       */
      public Category.Builder getCategoryBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCategoryFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protobuf.Category category = 2;</code>
       */
      public CategoryOrBuilder getCategoryOrBuilder() {
        if (categoryBuilder_ != null) {
          return categoryBuilder_.getMessageOrBuilder();
        } else {
          return category_;
        }
      }
      /**
       * <code>required .protobuf.Category category = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Category, Category.Builder, CategoryOrBuilder>
          getCategoryFieldBuilder() {
        if (categoryBuilder_ == null) {
          categoryBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Category, Category.Builder, CategoryOrBuilder>(
                  category_,
                  getParentForChildren(),
                  isClean());
          category_ = null;
        }
        return categoryBuilder_;
      }

      // required .protobuf.RequestMessage requestMessage = 3;
      private RequestMessage requestMessage_ = RequestMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          RequestMessage, RequestMessage.Builder, RequestMessageOrBuilder> requestMessageBuilder_;
      /**
       * <code>required .protobuf.RequestMessage requestMessage = 3;</code>
       */
      public boolean hasRequestMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .protobuf.RequestMessage requestMessage = 3;</code>
       */
      public RequestMessage getRequestMessage() {
        if (requestMessageBuilder_ == null) {
          return requestMessage_;
        } else {
          return requestMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protobuf.RequestMessage requestMessage = 3;</code>
       */
      public Builder setRequestMessage(RequestMessage value) {
        if (requestMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          requestMessage_ = value;
          onChanged();
        } else {
          requestMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .protobuf.RequestMessage requestMessage = 3;</code>
       */
      public Builder setRequestMessage(
          RequestMessage.Builder builderForValue) {
        if (requestMessageBuilder_ == null) {
          requestMessage_ = builderForValue.build();
          onChanged();
        } else {
          requestMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .protobuf.RequestMessage requestMessage = 3;</code>
       */
      public Builder mergeRequestMessage(RequestMessage value) {
        if (requestMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              requestMessage_ != RequestMessage.getDefaultInstance()) {
            requestMessage_ =
              RequestMessage.newBuilder(requestMessage_).mergeFrom(value).buildPartial();
          } else {
            requestMessage_ = value;
          }
          onChanged();
        } else {
          requestMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .protobuf.RequestMessage requestMessage = 3;</code>
       */
      public Builder clearRequestMessage() {
        if (requestMessageBuilder_ == null) {
          requestMessage_ = RequestMessage.getDefaultInstance();
          onChanged();
        } else {
          requestMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .protobuf.RequestMessage requestMessage = 3;</code>
       */
      public RequestMessage.Builder getRequestMessageBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getRequestMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protobuf.RequestMessage requestMessage = 3;</code>
       */
      public RequestMessageOrBuilder getRequestMessageOrBuilder() {
        if (requestMessageBuilder_ != null) {
          return requestMessageBuilder_.getMessageOrBuilder();
        } else {
          return requestMessage_;
        }
      }
      /**
       * <code>required .protobuf.RequestMessage requestMessage = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          RequestMessage, RequestMessage.Builder, RequestMessageOrBuilder>
          getRequestMessageFieldBuilder() {
        if (requestMessageBuilder_ == null) {
          requestMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              RequestMessage, RequestMessage.Builder, RequestMessageOrBuilder>(
                  requestMessage_,
                  getParentForChildren(),
                  isClean());
          requestMessage_ = null;
        }
        return requestMessageBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.QueueMsg)
    }

    static {
      defaultInstance = new QueueMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.QueueMsg)
  }

  public interface CategoryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string type = 1;
    /**
     * <code>required string type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 1;</code>
     */
    String getType();
    /**
     * <code>required string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    // required string name = 2;
    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code protobuf.Category}
   */
  public static final class Category extends
      com.google.protobuf.GeneratedMessage
      implements CategoryOrBuilder {
    // Use Category.newBuilder() to construct.
    private Category(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Category(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Category defaultInstance;
    public static Category getDefaultInstance() {
      return defaultInstance;
    }

    public Category getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Category(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              type_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QueueMsgProto.internal_static_protobuf_Category_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QueueMsgProto.internal_static_protobuf_Category_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Category.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Category> PARSER =
        new com.google.protobuf.AbstractParser<Category>() {
      public Category parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Category(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Category> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private Object type_;
    /**
     * <code>required string type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string type = 1;</code>
     */
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = "";
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Category parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Category parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Category parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Category parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Category parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Category parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Category parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Category parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Category parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Category parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Category prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Category}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CategoryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QueueMsgProto.internal_static_protobuf_Category_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QueueMsgProto.internal_static_protobuf_Category_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Category.class, Builder.class);
      }

      // Construct using group.chaoliu.lightchaser.rpc.netty.protobuf.QueueMsgProto.Category.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QueueMsgProto.internal_static_protobuf_Category_descriptor;
      }

      public Category getDefaultInstanceForType() {
        return Category.getDefaultInstance();
      }

      public Category build() {
        Category result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Category buildPartial() {
        Category result = new Category(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Category) {
          return mergeFrom((Category)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Category other) {
        if (other == Category.getDefaultInstance()) return this;
        if (other.hasType()) {
          bitField0_ |= 0x00000001;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Category parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Category) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string type = 1;
      private Object type_ = "";
      /**
       * <code>required string type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string type = 1;</code>
       */
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }

      // required string name = 2;
      private Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.Category)
    }

    static {
      defaultInstance = new Category(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.Category)
  }

  public interface RequestMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string URL = 1;
    /**
     * <code>required string URL = 1;</code>
     */
    boolean hasURL();
    /**
     * <code>required string URL = 1;</code>
     */
    String getURL();
    /**
     * <code>required string URL = 1;</code>
     */
    com.google.protobuf.ByteString
        getURLBytes();

    // optional bool isPostRequest = 2;
    /**
     * <code>optional bool isPostRequest = 2;</code>
     */
    boolean hasIsPostRequest();
    /**
     * <code>optional bool isPostRequest = 2;</code>
     */
    boolean getIsPostRequest();

    // repeated string headers = 3;
    /**
     * <code>repeated string headers = 3;</code>
     */
    java.util.List<String>
    getHeadersList();
    /**
     * <code>repeated string headers = 3;</code>
     */
    int getHeadersCount();
    /**
     * <code>repeated string headers = 3;</code>
     */
    String getHeaders(int index);
    /**
     * <code>repeated string headers = 3;</code>
     */
    com.google.protobuf.ByteString
        getHeadersBytes(int index);

    // repeated string cookie = 4;
    /**
     * <code>repeated string cookie = 4;</code>
     */
    java.util.List<String>
    getCookieList();
    /**
     * <code>repeated string cookie = 4;</code>
     */
    int getCookieCount();
    /**
     * <code>repeated string cookie = 4;</code>
     */
    String getCookie(int index);
    /**
     * <code>repeated string cookie = 4;</code>
     */
    com.google.protobuf.ByteString
        getCookieBytes(int index);
  }
  /**
   * Protobuf type {@code protobuf.RequestMessage}
   */
  public static final class RequestMessage extends
      com.google.protobuf.GeneratedMessage
      implements RequestMessageOrBuilder {
    // Use RequestMessage.newBuilder() to construct.
    private RequestMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RequestMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RequestMessage defaultInstance;
    public static RequestMessage getDefaultInstance() {
      return defaultInstance;
    }

    public RequestMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              uRL_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isPostRequest_ = input.readBool();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                headers_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              headers_.add(input.readBytes());
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                cookie_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              cookie_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          headers_ = new com.google.protobuf.UnmodifiableLazyStringList(headers_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          cookie_ = new com.google.protobuf.UnmodifiableLazyStringList(cookie_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QueueMsgProto.internal_static_protobuf_RequestMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QueueMsgProto.internal_static_protobuf_RequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RequestMessage.class, Builder.class);
    }

    public static com.google.protobuf.Parser<RequestMessage> PARSER =
        new com.google.protobuf.AbstractParser<RequestMessage>() {
      public RequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestMessage(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<RequestMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string URL = 1;
    public static final int URL_FIELD_NUMBER = 1;
    private Object uRL_;
    /**
     * <code>required string URL = 1;</code>
     */
    public boolean hasURL() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string URL = 1;</code>
     */
    public String getURL() {
      Object ref = uRL_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uRL_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string URL = 1;</code>
     */
    public com.google.protobuf.ByteString
        getURLBytes() {
      Object ref = uRL_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        uRL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bool isPostRequest = 2;
    public static final int ISPOSTREQUEST_FIELD_NUMBER = 2;
    private boolean isPostRequest_;
    /**
     * <code>optional bool isPostRequest = 2;</code>
     */
    public boolean hasIsPostRequest() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool isPostRequest = 2;</code>
     */
    public boolean getIsPostRequest() {
      return isPostRequest_;
    }

    // repeated string headers = 3;
    public static final int HEADERS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList headers_;
    /**
     * <code>repeated string headers = 3;</code>
     */
    public java.util.List<String>
        getHeadersList() {
      return headers_;
    }
    /**
     * <code>repeated string headers = 3;</code>
     */
    public int getHeadersCount() {
      return headers_.size();
    }
    /**
     * <code>repeated string headers = 3;</code>
     */
    public String getHeaders(int index) {
      return headers_.get(index);
    }
    /**
     * <code>repeated string headers = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHeadersBytes(int index) {
      return headers_.getByteString(index);
    }

    // repeated string cookie = 4;
    public static final int COOKIE_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList cookie_;
    /**
     * <code>repeated string cookie = 4;</code>
     */
    public java.util.List<String>
        getCookieList() {
      return cookie_;
    }
    /**
     * <code>repeated string cookie = 4;</code>
     */
    public int getCookieCount() {
      return cookie_.size();
    }
    /**
     * <code>repeated string cookie = 4;</code>
     */
    public String getCookie(int index) {
      return cookie_.get(index);
    }
    /**
     * <code>repeated string cookie = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCookieBytes(int index) {
      return cookie_.getByteString(index);
    }

    private void initFields() {
      uRL_ = "";
      isPostRequest_ = false;
      headers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      cookie_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasURL()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getURLBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isPostRequest_);
      }
      for (int i = 0; i < headers_.size(); i++) {
        output.writeBytes(3, headers_.getByteString(i));
      }
      for (int i = 0; i < cookie_.size(); i++) {
        output.writeBytes(4, cookie_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getURLBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isPostRequest_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < headers_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(headers_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getHeadersList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < cookie_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(cookie_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getCookieList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static RequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static RequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static RequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(RequestMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.RequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements RequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QueueMsgProto.internal_static_protobuf_RequestMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QueueMsgProto.internal_static_protobuf_RequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RequestMessage.class, Builder.class);
      }

      // Construct using group.chaoliu.lightchaser.rpc.netty.protobuf.QueueMsgProto.RequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uRL_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        isPostRequest_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        headers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        cookie_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QueueMsgProto.internal_static_protobuf_RequestMessage_descriptor;
      }

      public RequestMessage getDefaultInstanceForType() {
        return RequestMessage.getDefaultInstance();
      }

      public RequestMessage build() {
        RequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RequestMessage buildPartial() {
        RequestMessage result = new RequestMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uRL_ = uRL_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isPostRequest_ = isPostRequest_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          headers_ = new com.google.protobuf.UnmodifiableLazyStringList(
              headers_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.headers_ = headers_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          cookie_ = new com.google.protobuf.UnmodifiableLazyStringList(
              cookie_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.cookie_ = cookie_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RequestMessage) {
          return mergeFrom((RequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RequestMessage other) {
        if (other == RequestMessage.getDefaultInstance()) return this;
        if (other.hasURL()) {
          bitField0_ |= 0x00000001;
          uRL_ = other.uRL_;
          onChanged();
        }
        if (other.hasIsPostRequest()) {
          setIsPostRequest(other.getIsPostRequest());
        }
        if (!other.headers_.isEmpty()) {
          if (headers_.isEmpty()) {
            headers_ = other.headers_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureHeadersIsMutable();
            headers_.addAll(other.headers_);
          }
          onChanged();
        }
        if (!other.cookie_.isEmpty()) {
          if (cookie_.isEmpty()) {
            cookie_ = other.cookie_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureCookieIsMutable();
            cookie_.addAll(other.cookie_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasURL()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RequestMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string URL = 1;
      private Object uRL_ = "";
      /**
       * <code>required string URL = 1;</code>
       */
      public boolean hasURL() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string URL = 1;</code>
       */
      public String getURL() {
        Object ref = uRL_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uRL_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string URL = 1;</code>
       */
      public com.google.protobuf.ByteString
          getURLBytes() {
        Object ref = uRL_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          uRL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string URL = 1;</code>
       */
      public Builder setURL(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uRL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string URL = 1;</code>
       */
      public Builder clearURL() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uRL_ = getDefaultInstance().getURL();
        onChanged();
        return this;
      }
      /**
       * <code>required string URL = 1;</code>
       */
      public Builder setURLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uRL_ = value;
        onChanged();
        return this;
      }

      // optional bool isPostRequest = 2;
      private boolean isPostRequest_ ;
      /**
       * <code>optional bool isPostRequest = 2;</code>
       */
      public boolean hasIsPostRequest() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool isPostRequest = 2;</code>
       */
      public boolean getIsPostRequest() {
        return isPostRequest_;
      }
      /**
       * <code>optional bool isPostRequest = 2;</code>
       */
      public Builder setIsPostRequest(boolean value) {
        bitField0_ |= 0x00000002;
        isPostRequest_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isPostRequest = 2;</code>
       */
      public Builder clearIsPostRequest() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isPostRequest_ = false;
        onChanged();
        return this;
      }

      // repeated string headers = 3;
      private com.google.protobuf.LazyStringList headers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureHeadersIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          headers_ = new com.google.protobuf.LazyStringArrayList(headers_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string headers = 3;</code>
       */
      public java.util.List<String>
          getHeadersList() {
        return java.util.Collections.unmodifiableList(headers_);
      }
      /**
       * <code>repeated string headers = 3;</code>
       */
      public int getHeadersCount() {
        return headers_.size();
      }
      /**
       * <code>repeated string headers = 3;</code>
       */
      public String getHeaders(int index) {
        return headers_.get(index);
      }
      /**
       * <code>repeated string headers = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHeadersBytes(int index) {
        return headers_.getByteString(index);
      }
      /**
       * <code>repeated string headers = 3;</code>
       */
      public Builder setHeaders(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHeadersIsMutable();
        headers_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string headers = 3;</code>
       */
      public Builder addHeaders(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHeadersIsMutable();
        headers_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string headers = 3;</code>
       */
      public Builder addAllHeaders(
          Iterable<String> values) {
        ensureHeadersIsMutable();
        super.addAll(values, headers_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string headers = 3;</code>
       */
      public Builder clearHeaders() {
        headers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string headers = 3;</code>
       */
      public Builder addHeadersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHeadersIsMutable();
        headers_.add(value);
        onChanged();
        return this;
      }

      // repeated string cookie = 4;
      private com.google.protobuf.LazyStringList cookie_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCookieIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          cookie_ = new com.google.protobuf.LazyStringArrayList(cookie_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string cookie = 4;</code>
       */
      public java.util.List<String>
          getCookieList() {
        return java.util.Collections.unmodifiableList(cookie_);
      }
      /**
       * <code>repeated string cookie = 4;</code>
       */
      public int getCookieCount() {
        return cookie_.size();
      }
      /**
       * <code>repeated string cookie = 4;</code>
       */
      public String getCookie(int index) {
        return cookie_.get(index);
      }
      /**
       * <code>repeated string cookie = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCookieBytes(int index) {
        return cookie_.getByteString(index);
      }
      /**
       * <code>repeated string cookie = 4;</code>
       */
      public Builder setCookie(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCookieIsMutable();
        cookie_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string cookie = 4;</code>
       */
      public Builder addCookie(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCookieIsMutable();
        cookie_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string cookie = 4;</code>
       */
      public Builder addAllCookie(
          Iterable<String> values) {
        ensureCookieIsMutable();
        super.addAll(values, cookie_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string cookie = 4;</code>
       */
      public Builder clearCookie() {
        cookie_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string cookie = 4;</code>
       */
      public Builder addCookieBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCookieIsMutable();
        cookie_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.RequestMessage)
    }

    static {
      defaultInstance = new RequestMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.RequestMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_QueueMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_QueueMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Category_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Category_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_RequestMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_RequestMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016QueueMsg.proto\022\010protobuf\"t\n\010QueueMsg\022\020" +
      "\n\010URLLevel\030\001 \002(\005\022$\n\010category\030\002 \002(\0132\022.pro" +
      "tobuf.Category\0220\n\016requestMessage\030\003 \002(\0132\030" +
      ".protobuf.RequestMessage\"&\n\010Category\022\014\n\004" +
      "type\030\001 \002(\t\022\014\n\004name\030\002 \002(\t\"U\n\016RequestMessa" +
      "ge\022\013\n\003URL\030\001 \002(\t\022\025\n\risPostRequest\030\002 \001(\010\022\017" +
      "\n\007headers\030\003 \003(\t\022\016\n\006cookie\030\004 \003(\tB=\n,group" +
      ".chaoliu.lightchaser.rpc.netty.protobufB" +
      "\rQueueMsgProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_QueueMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_QueueMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_QueueMsg_descriptor,
              new String[] { "URLLevel", "Category", "RequestMessage", });
          internal_static_protobuf_Category_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobuf_Category_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_Category_descriptor,
              new String[] { "Type", "Name", });
          internal_static_protobuf_RequestMessage_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_protobuf_RequestMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_RequestMessage_descriptor,
              new String[] { "URL", "IsPostRequest", "Headers", "Cookie", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
